
"""
chroma_store.py

Purpose:
--------
Store precomputed multilingual document embeddings in ChromaDB
and provide vector similarity search for the RAG pipeline.

Input:
------
data/processed/embeddings.json

Persistent Database:
--------------------
data/vector_db/chroma/

Pipeline:
---------
PDFs
    ↓
pdf_extractor.py
    ↓
text_cleaner.py
    ↓
metadata_builder.py
    ↓
chunker.py
    ↓
chunks.json
    ↓
embedding_service.py
    ↓
embeddings.json
    ↓
chroma_store.py
    ↓
Persistent ChromaDB
    ↓
retriever.py
    ↓
RAG Pipeline

Important:
----------
Embeddings have already been generated by embedding_service.py
using:

sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2

Therefore this module does NOT ask ChromaDB to generate embeddings.

Instead, it directly stores:

- chunk_id
- document text
- embedding vector
- metadata

During retrieval, the user query must be embedded using the SAME
embedding model before calling search().

Required package:
-----------------
pip install chromadb

Run:
----
python vectorstore/chroma_store.py
"""

import json
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

import chromadb


# ============================================================
# Configuration
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parent.parent

DATA_DIR = PROJECT_ROOT / "data"

PROCESSED_DIR = DATA_DIR / "processed"

EMBEDDINGS_FILE = (
    PROCESSED_DIR
    / "embeddings.json"
)

VECTOR_DB_DIR = (
    DATA_DIR
    / "vector_db"
    / "chroma"
)


# ============================================================
# Chroma Configuration
# ============================================================

DEFAULT_COLLECTION_NAME = (
    "pds_welfare_knowledge"
)

DEFAULT_BATCH_SIZE = 100

DEFAULT_TOP_K = 5


# ============================================================
# Logging
# ============================================================

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
)

logger = logging.getLogger(
    __name__
)


# ============================================================
# Chroma Vector Store
# ============================================================

class ChromaStore:
    """
    Persistent ChromaDB vector store.

    Responsibilities:
    -----------------
    1. Initialize persistent ChromaDB.
    2. Create/get the RAG collection.
    3. Load embeddings.json.
    4. Insert/upsert chunks and embeddings.
    5. Search using query embeddings.
    6. Support metadata filtering.
    7. Retrieve collection statistics.
    8. Delete/reset collection when needed.

    Important:
    ----------
    This class does NOT generate embeddings.

    Embeddings are generated by:

        embeddings/embedding_service.py

    This ensures document chunks and user queries use exactly
    the same multilingual embedding model.
    """

    def __init__(
        self,
        persist_directory: Path = VECTOR_DB_DIR,
        collection_name: str = DEFAULT_COLLECTION_NAME,
        embeddings_file: Path = EMBEDDINGS_FILE,
    ) -> None:

        self.persist_directory = Path(
            persist_directory
        )

        self.collection_name = (
            collection_name
        )

        self.embeddings_file = Path(
            embeddings_file
        )

        # Create database directory
        self.persist_directory.mkdir(
            parents=True,
            exist_ok=True,
        )

        logger.info(
            "Initializing ChromaDB"
        )

        logger.info(
            "Database directory: %s",
            self.persist_directory,
        )

        logger.info(
            "Collection: %s",
            self.collection_name,
        )

        # ----------------------------------------------------
        # Persistent Chroma Client
        # ----------------------------------------------------

        self.client = (
            chromadb.PersistentClient(
                path=str(
                    self.persist_directory
                )
            )
        )

        # ----------------------------------------------------
        # Create or load collection
        #
        # No embedding_function is supplied because we provide
        # embeddings ourselves.
        #
        # cosine space matches normalized sentence-transformer
        # embeddings well.
        # ----------------------------------------------------

        self.collection = (
            self.client.get_or_create_collection(
                name=self.collection_name,
                metadata={
    "hnsw:space": "cosine",
    "description": (
        "PDS and social welfare "
        "multilingual RAG knowledge base"
    ),
}
            )
        )

        logger.info(
            "ChromaDB initialized successfully"
        )

        logger.info(
            "Existing records: %d",
            self.collection.count(),
        )

    # ========================================================
    # Load Embeddings JSON
    # ========================================================

    def load_embeddings(
        self,
    ) -> List[Dict[str, Any]]:
        """
        Load embedded chunks from embeddings.json.

        Expected structure:

        {
            "embedding_info": {...},
            "summary": {...},
            "chunks": [
                {
                    "chunk_id": "...",
                    "text": "...",
                    "embedding": [...],
                    "metadata": {...}
                }
            ]
        }
        """

        if not self.embeddings_file.exists():

            raise FileNotFoundError(
                f"Embeddings file not found: "
                f"{self.embeddings_file}"
            )

        logger.info(
            "Loading embeddings from: %s",
            self.embeddings_file,
        )

        with self.embeddings_file.open(
            "r",
            encoding="utf-8",
        ) as file:

            data = json.load(
                file
            )

        if isinstance(
            data,
            dict,
        ):

            chunks = data.get(
                "chunks",
                [],
            )

        elif isinstance(
            data,
            list,
        ):

            chunks = data

        else:

            raise ValueError(
                "Invalid embeddings.json structure."
            )

        logger.info(
            "Loaded %d embedded chunk(s)",
            len(chunks),
        )

        return chunks

    # ========================================================
    # Metadata Sanitization
    # ========================================================

    @staticmethod
    def sanitize_metadata(
        metadata: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Ensure metadata contains values ChromaDB can store.

        Supported simple metadata types:

        - str
        - int
        - float
        - bool

        None values are removed.

        Lists/dictionaries are converted to strings as a safe
        fallback for this project's metadata structure.
        """

        if not metadata:

            return {}

        sanitized = {}

        for key, value in metadata.items():

            if value is None:

                continue

            if isinstance(
                value,
                (
                    str,
                    int,
                    float,
                    bool,
                ),
            ):

                sanitized[
                    str(key)
                ] = value

            elif isinstance(
                value,
                list,
            ):

                sanitized[
                    str(key)
                ] = ", ".join(
                    str(item)
                    for item in value
                )

            elif isinstance(
                value,
                dict,
            ):

                sanitized[
                    str(key)
                ] = json.dumps(
                    value,
                    ensure_ascii=False,
                )

            else:

                sanitized[
                    str(key)
                ] = str(
                    value
                )

        return sanitized

    # ========================================================
    # Validate Embedded Chunk
    # ========================================================

    @staticmethod
    def is_valid_chunk(
        chunk: Dict[str, Any],
    ) -> bool:
        """
        Validate an embedded chunk before insertion.
        """

        chunk_id = chunk.get(
            "chunk_id"
        )

        text = chunk.get(
            "text"
        )

        embedding = chunk.get(
            "embedding"
        )

        if not chunk_id:

            return False

        if (
            not isinstance(
                text,
                str,
            )
            or not text.strip()
        ):

            return False

        if (
            not isinstance(
                embedding,
                list,
            )
            or not embedding
        ):

            return False

        return True

    # ========================================================
    # Insert / Upsert Embedded Chunks
    # ========================================================

    def upsert_chunks(
        self,
        chunks: List[
            Dict[str, Any]
        ],
        batch_size: int = DEFAULT_BATCH_SIZE,
    ) -> Dict[str, int]:
        """
        Insert or update chunks in ChromaDB.

        upsert() is used instead of add().

        This allows the ingestion pipeline to be run multiple
        times without failing because of existing chunk IDs.
        """

        if batch_size <= 0:

            raise ValueError(
                "batch_size must be greater than 0."
            )

        valid_chunks = []

        invalid_chunks = 0

        for chunk in chunks:

            if self.is_valid_chunk(
                chunk
            ):

                valid_chunks.append(
                    chunk
                )

            else:

                invalid_chunks += 1

                logger.warning(
                    "Skipping invalid embedded chunk: %s",
                    chunk.get(
                        "chunk_id",
                        "unknown",
                    ),
                )

        if not valid_chunks:

            logger.warning(
                "No valid chunks available for ingestion."
            )

            return {
                "inserted_or_updated": 0,
                "invalid_chunks": (
                    invalid_chunks
                ),
            }

        logger.info(
            "Upserting %d chunks into ChromaDB",
            len(valid_chunks),
        )

        total_processed = 0

        # ----------------------------------------------------
        # Batch ingestion
        # ----------------------------------------------------

        for start in range(
            0,
            len(valid_chunks),
            batch_size,
        ):

            end = min(
                start + batch_size,
                len(valid_chunks),
            )

            batch = valid_chunks[
                start:end
            ]

            ids = []

            documents = []

            embeddings = []

            metadatas = []

            for chunk in batch:

                ids.append(
                    str(
                        chunk[
                            "chunk_id"
                        ]
                    )
                )

                documents.append(
                    chunk[
                        "text"
                    ]
                )

                embeddings.append(
                    chunk[
                        "embedding"
                    ]
                )

                metadata = (
                    self.sanitize_metadata(
                        chunk.get(
                            "metadata",
                            {},
                        )
                    )
                )

                # Store useful statistics too
                metadata[
                    "word_count"
                ] = int(
                    chunk.get(
                        "word_count",
                        len(
                            chunk[
                                "text"
                            ].split()
                        ),
                    )
                )

                metadata[
                    "character_count"
                ] = int(
                    chunk.get(
                        "character_count",
                        len(
                            chunk[
                                "text"
                            ]
                        ),
                    )
                )

                metadatas.append(
                    metadata
                )

            # ------------------------------------------------
            # Upsert batch
            # ------------------------------------------------

            self.collection.upsert(
                ids=ids,
                documents=documents,
                embeddings=embeddings,
                metadatas=metadatas,
            )

            total_processed += len(
                batch
            )

            logger.info(
                "Processed %d/%d chunks",
                total_processed,
                len(valid_chunks),
            )

        logger.info(
            "ChromaDB ingestion completed"
        )

        logger.info(
            "Collection now contains %d records",
            self.collection.count(),
        )

        return {
            "inserted_or_updated": (
                total_processed
            ),

            "invalid_chunks": (
                invalid_chunks
            ),
        }

    # ========================================================
    # Ingest embeddings.json
    # ========================================================

    def ingest_embeddings(
        self,
        batch_size: int = DEFAULT_BATCH_SIZE,
    ) -> Dict[str, Any]:
        """
        Complete ingestion flow:

        embeddings.json
            ↓
        Load embedded chunks
            ↓
        Validate
            ↓
        Batch upsert
            ↓
        Persistent ChromaDB
        """

        chunks = (
            self.load_embeddings()
        )

        if not chunks:

            logger.warning(
                "No embedded chunks found."
            )

            return {
                "total_input_chunks": 0,
                "inserted_or_updated": 0,
                "invalid_chunks": 0,
                "collection_count": (
                    self.collection.count()
                ),
            }

        result = self.upsert_chunks(
            chunks=chunks,
            batch_size=batch_size,
        )

        return {
            "total_input_chunks": len(
                chunks
            ),

            "inserted_or_updated": (
                result[
                    "inserted_or_updated"
                ]
            ),

            "invalid_chunks": (
                result[
                    "invalid_chunks"
                ]
            ),

            "collection_count": (
                self.collection.count()
            ),
        }

    # ========================================================
    # Vector Search
    # ========================================================

    def search(
        self,
        query_embedding: List[float],
        top_k: int = DEFAULT_TOP_K,
        where: Optional[
            Dict[str, Any]
        ] = None,
    ) -> List[Dict[str, Any]]:
        """
        Perform vector similarity search.

        Parameters
        ----------
        query_embedding:
            Embedding generated by EmbeddingService.embed_query().

        top_k:
            Number of nearest chunks to return.

        where:
            Optional ChromaDB metadata filter.

        Examples
        --------

        No filter:

            search(
                query_embedding=query_vector,
                top_k=5
            )

        Filter by state:

            search(
                query_embedding=query_vector,
                top_k=5,
                where={
                    "state": "uttar_pradesh"
                }
            )

        Filter by category:

            search(
                query_embedding=query_vector,
                where={
                    "category": "PDS"
                }
            )
        """

        if not query_embedding:

            raise ValueError(
                "query_embedding cannot be empty."
            )

        if top_k <= 0:

            raise ValueError(
                "top_k must be greater than 0."
            )

        collection_count = (
            self.collection.count()
        )

        if collection_count == 0:

            logger.warning(
                "ChromaDB collection is empty."
            )

            return []

        # Avoid requesting more results than available
        n_results = min(
            top_k,
            collection_count,
        )

        query_arguments = {
            "query_embeddings": [
                query_embedding
            ],

            "n_results": (
                n_results
            ),

            "include": [
                "documents",
                "metadatas",
                "distances",
            ],
        }

        if where:

            query_arguments[
                "where"
            ] = where

        results = (
            self.collection.query(
                **query_arguments
            )
        )

        return self._format_search_results(
            results
        )

    # ========================================================
    # Format Search Results
    # ========================================================

    @staticmethod
    def _format_search_results(
        results: Dict[str, Any],
    ) -> List[Dict[str, Any]]:
        """
        Convert Chroma's nested query response into a simpler
        list of result dictionaries.
        """

        formatted_results = []

        ids = (
            results.get(
                "ids",
                [[]],
            )[0]
            or []
        )

        documents = (
            results.get(
                "documents",
                [[]],
            )[0]
            or []
        )

        metadatas = (
            results.get(
                "metadatas",
                [[]],
            )[0]
            or []
        )

        distances = (
            results.get(
                "distances",
                [[]],
            )[0]
            or []
        )

        for index, chunk_id in enumerate(
            ids
        ):

            document = (
                documents[index]
                if index < len(
                    documents
                )
                else ""
            )

            metadata = (
                metadatas[index]
                if index < len(
                    metadatas
                )
                else {}
            )

            distance = (
                distances[index]
                if index < len(
                    distances
                )
                else None
            )

            # With cosine distance:
            #
            # similarity ≈ 1 - distance
            #
            # This is mainly useful for debugging and ranking
            # display. Treat it as a retrieval score rather
            # than an absolute confidence score.

            similarity = None

            if distance is not None:

                similarity = (
                    1.0
                    - float(
                        distance
                    )
                )

            formatted_results.append(
                {
                    "chunk_id": (
                        chunk_id
                    ),

                    "text": (
                        document
                    ),

                    "metadata": (
                        metadata
                    ),

                    "distance": (
                        float(
                            distance
                        )
                        if distance
                        is not None
                        else None
                    ),

                    "similarity": (
                        similarity
                    ),
                }
            )

        return formatted_results

    # ========================================================
    # Get Chunk by ID
    # ========================================================

    def get_by_id(
        self,
        chunk_id: str,
    ) -> Optional[
        Dict[str, Any]
    ]:
        """
        Retrieve a chunk directly by its ID.
        """

        if not chunk_id:

            raise ValueError(
                "chunk_id cannot be empty."
            )

        result = (
            self.collection.get(
                ids=[
                    chunk_id
                ],

                include=[
                    "documents",
                    "metadatas",
                ],
            )
        )

        ids = result.get(
            "ids",
            [],
        )

        if not ids:

            return None

        documents = result.get(
            "documents",
            [],
        )

        metadatas = result.get(
            "metadatas",
            [],
        )

        return {
            "chunk_id": ids[0],

            "text": (
                documents[0]
                if documents
                else ""
            ),

            "metadata": (
                metadatas[0]
                if metadatas
                else {}
            ),
        }

    # ========================================================
    # Get Collection Count
    # ========================================================

    def count(
        self,
    ) -> int:
        """
        Return number of records in collection.
        """

        return (
            self.collection.count()
        )

    # ========================================================
    # Collection Information
    # ========================================================

    def get_collection_info(
        self,
    ) -> Dict[str, Any]:
        """
        Return basic collection information.
        """

        return {
            "collection_name": (
                self.collection_name
            ),

            "persist_directory": str(
                self.persist_directory
            ),

            "record_count": (
                self.collection.count()
            ),
        }

    # ========================================================
    # Reset Collection
    # ========================================================

    def reset_collection(
        self,
    ) -> None:
        """
        Delete and recreate the collection.

        WARNING:
        --------
        This removes all indexed chunks.

        Useful during development when rebuilding the entire
        knowledge base.
        """

        logger.warning(
            "Resetting ChromaDB collection: %s",
            self.collection_name,
        )

        try:

            self.client.delete_collection(
                name=self.collection_name
            )

        except Exception:

            logger.info(
                "Collection did not exist "
                "or could not be deleted."
            )

        self.collection = (
            self.client.get_or_create_collection(
                name=self.collection_name,

                configuration={
                    "hnsw": {
                        "space": "cosine"
                    }
                },

                metadata={
                    "description": (
                        "PDS and social welfare "
                        "multilingual RAG knowledge base"
                    )
                },
            )
        )

        logger.info(
            "Collection reset successfully"
        )


# ============================================================
# Main
# ============================================================

def main() -> None:
    """
    Run ChromaDB ingestion directly.
    """

    print(
        "\n"
        + "=" * 60
    )

    print(
        "PDS & SOCIAL WELFARE AI "
        "- CHROMADB INGESTION"
    )

    print(
        "=" * 60
    )

    store = ChromaStore()

    print(
        "\nInitial Collection"
    )

    print(
        "-" * 60
    )

    initial_info = (
        store.get_collection_info()
    )

    print(
        f"Collection : "
        f"{initial_info['collection_name']}"
    )

    print(
        f"Records    : "
        f"{initial_info['record_count']}"
    )

    print(
        f"Database   : "
        f"{initial_info['persist_directory']}"
    )

    # --------------------------------------------------------
    # Ingest embeddings
    # --------------------------------------------------------

    result = (
        store.ingest_embeddings()
    )

    print(
        "\nIngestion Summary"
    )

    print(
        "-" * 60
    )

    print(
        f"Input chunks       : "
        f"{result['total_input_chunks']}"
    )

    print(
        f"Inserted / Updated : "
        f"{result['inserted_or_updated']}"
    )

    print(
        f"Invalid chunks     : "
        f"{result['invalid_chunks']}"
    )

    print(
        f"Collection records : "
        f"{result['collection_count']}"
    )

    print(
        "\nChromaDB directory:"
    )

    print(
        VECTOR_DB_DIR
    )

    print(
        "\n"
        + "=" * 60
    )


if __name__ == "__main__":
    main()

