import type { Lang } from "@/lib/i18n";

const copy = {
  en: {
    my: "My Checklists",
    active: "Active",
    archived: "Archived",
    empty: "No saved checklists yet.",
    emptyHelp: "Generate a service checklist and save it to track your progress.",
    loading: "Loading checklists…",
    completed: "completed",
    updated: "Last updated",
    open: "Continue",
    save: "Save Checklist",
    saving: "Saving…",
    saved: "Checklist saved.",
    archive: "Archive",
    restore: "Restore",
    delete: "Delete",
    refresh: "Check for source updates",
    note: "General progress note",
    noteWarning: "Do not enter Aadhaar, bank, OTP, password, or document numbers.",
    required: "Required",
    optional: "Optional",
    sources: "Official evidence sources",
    guidance: "Personalized next steps",
    importTitle: "Import your guest checklists?",
    importBody: "You created checklists before logging in. Import them into this account only if you approve.",
    import: "Import checklists",
    skip: "Not now",
  },
  hi: {
    my: "मेरी चेकलिस्ट",
    active: "सक्रिय",
    archived: "संग्रहित",
    empty: "अभी कोई सहेजी गई चेकलिस्ट नहीं है।",
    emptyHelp: "प्रगति देखने के लिए सेवा चेकलिस्ट बनाकर सहेजें।",
    loading: "चेकलिस्ट लोड हो रही हैं…",
    completed: "पूर्ण",
    updated: "अंतिम अपडेट",
    open: "जारी रखें",
    save: "चेकलिस्ट सहेजें",
    saving: "सहेजा जा रहा है…",
    saved: "चेकलिस्ट सहेजी गई।",
    archive: "संग्रहित करें",
    restore: "पुनर्स्थापित करें",
    delete: "हटाएँ",
    refresh: "स्रोत अपडेट जाँचें",
    note: "सामान्य प्रगति नोट",
    noteWarning: "आधार, बैंक, OTP, पासवर्ड या दस्तावेज़ नंबर दर्ज न करें।",
    required: "आवश्यक",
    optional: "वैकल्पिक",
    sources: "आधिकारिक प्रमाण स्रोत",
    guidance: "व्यक्तिगत अगले कदम",
    importTitle: "अपनी अतिथि चेकलिस्ट आयात करें?",
    importBody: "आपने लॉगिन से पहले चेकलिस्ट बनाई थीं। केवल अपनी अनुमति से उन्हें इस खाते में आयात करें।",
    import: "चेकलिस्ट आयात करें",
    skip: "अभी नहीं",
  },
  hinglish: {
    my: "Meri Checklists",
    active: "Active",
    archived: "Archived",
    empty: "Abhi koi saved checklist nahi hai.",
    emptyHelp: "Progress track karne ke liye service checklist generate karke save karein.",
    loading: "Checklists load ho rahi hain…",
    completed: "complete",
    updated: "Last update",
    open: "Continue karein",
    save: "Checklist Save karein",
    saving: "Save ho rahi hai…",
    saved: "Checklist save ho gayi.",
    archive: "Archive",
    restore: "Restore",
    delete: "Delete",
    refresh: "Source updates check karein",
    note: "General progress note",
    noteWarning: "Aadhaar, bank, OTP, password ya document number enter na karein.",
    required: "Required",
    optional: "Optional",
    sources: "Official evidence sources",
    guidance: "Personalized next steps",
    importTitle: "Guest checklists import karein?",
    importBody: "Aapne login se pehle checklists banayi thi. Sirf approval dene par unhe account mein import kiya jayega.",
    import: "Checklists import karein",
    skip: "Abhi nahi",
  },
} as const;

export function checklistCopy(lang: Lang) {
  return copy[lang];
}
