
"""
text_cleaner.py

Purpose:
--------
Clean page-level text extracted from PDF files.

This script reads JSON files generated by:

    preprocessing/pdf_extractor.py

Input:
------
data/extracted/
    document1.json
    document2.json
    document3.json

Output:
-------
data/processed/cleaned/
    document1.json
    document2.json
    document3.json

The cleaner:
------------
- Preserves document metadata
- Preserves page numbers
- Preserves Hindi/Unicode text
- Normalizes Unicode
- Removes null/control characters
- Normalizes line endings
- Removes excessive spaces and tabs
- Removes excessive blank lines
- Repairs common PDF line-break issues
- Repairs hyphenated words split across lines
- Removes simple page-number-only lines
- Keeps headings, numbered sections, bullets, and lists
- Skips OCR-required/empty pages safely
- Produces cleaning statistics
- Processes all extracted JSON files automatically

Run:
----
python preprocessing/text_cleaner.py
"""

import json
import logging
import re
import unicodedata
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional


# ============================================================
# Configuration
# ============================================================

# Current file:
# backend/preprocessing/text_cleaner.py
#
# PROJECT_ROOT:
# backend/
PROJECT_ROOT = Path(__file__).resolve().parent.parent

DATA_DIR = PROJECT_ROOT / "data"

EXTRACTED_DIR = DATA_DIR / "extracted"

PROCESSED_DIR = DATA_DIR / "processed"

CLEANED_DIR = PROCESSED_DIR / "cleaned"


# ============================================================
# Logging Configuration
# ============================================================

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
)

logger = logging.getLogger(__name__)


# ============================================================
# Text Cleaner
# ============================================================

class TextCleaner:
    """
    Cleans text extracted from PDF documents.

    This class intentionally performs conservative cleaning.

    Government and welfare documents often contain:

    - Section numbers
    - Bullet lists
    - Document checklists
    - Numbered application steps
    - Tables represented as text
    - Headings

    Aggressive cleaning can destroy useful information, so this
    cleaner focuses primarily on formatting noise.
    """

    def __init__(
        self,
        input_dir: Path = EXTRACTED_DIR,
        output_dir: Path = CLEANED_DIR,
    ) -> None:

        self.input_dir = Path(input_dir)
        self.output_dir = Path(output_dir)

        self.input_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        self.output_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        logger.info("TextCleaner initialized")
        logger.info(
            "Input directory: %s",
            self.input_dir,
        )
        logger.info(
            "Output directory: %s",
            self.output_dir,
        )

    # ========================================================
    # File Discovery
    # ========================================================

    def find_json_files(self) -> List[Path]:
        """
        Find all JSON files generated by pdf_extractor.py.
        """

        json_files = sorted(
            [
                file
                for file in self.input_dir.iterdir()
                if file.is_file()
                and file.suffix.lower() == ".json"
            ],
            key=lambda path: path.name.lower(),
        )

        logger.info(
            "Found %d extracted JSON file(s)",
            len(json_files),
        )

        return json_files

    # ========================================================
    # Basic Cleaning Utilities
    # ========================================================

    @staticmethod
    def normalize_unicode(text: str) -> str:
        """
        Normalize Unicode characters.

        NFKC normalization helps standardize visually equivalent
        Unicode representations while preserving Hindi and other
        Unicode languages.
        """

        if not text:
            return ""

        return unicodedata.normalize(
            "NFKC",
            text,
        )

    @staticmethod
    def remove_control_characters(text: str) -> str:
        """
        Remove unwanted control characters while preserving:

        - newline
        - tab

        This avoids deleting valid Unicode characters.
        """

        if not text:
            return ""

        cleaned_characters = []

        for char in text:

            if char in ("\n", "\t"):
                cleaned_characters.append(char)
                continue

            category = unicodedata.category(char)

            # Unicode category "C" includes control characters,
            # formatting characters, surrogates, etc.
            if not category.startswith("C"):
                cleaned_characters.append(char)

        return "".join(cleaned_characters)

    @staticmethod
    def normalize_line_endings(text: str) -> str:
        """
        Convert Windows and old Mac line endings into \\n.
        """

        if not text:
            return ""

        text = text.replace("\r\n", "\n")
        text = text.replace("\r", "\n")

        return text

    @staticmethod
    def normalize_spaces(text: str) -> str:
        """
        Normalize horizontal whitespace.

        Multiple spaces and tabs are converted into a single space.

        Newlines are preserved.
        """

        if not text:
            return ""

        lines = text.split("\n")

        cleaned_lines = []

        for line in lines:

            # Replace tabs with spaces
            line = line.replace("\t", " ")

            # Replace multiple spaces with one
            line = re.sub(
                r"[ ]{2,}",
                " ",
                line,
            )

            cleaned_lines.append(
                line.strip()
            )

        return "\n".join(cleaned_lines)

    # ========================================================
    # PDF-Specific Cleaning
    # ========================================================

    @staticmethod
    def remove_page_number_lines(text: str) -> str:
        """
        Remove lines that contain only a page number.

        Examples removed:
            1
            25
            Page 1
            Page 1 of 20
            Page 1/20

        This does NOT remove numbers appearing inside normal text.
        """

        if not text:
            return ""

        patterns = [
            r"^\s*\d+\s*$",
            r"^\s*page\s+\d+\s*$",
            r"^\s*page\s+\d+\s+of\s+\d+\s*$",
            r"^\s*page\s+\d+\s*/\s*\d+\s*$",
        ]

        cleaned_lines = []

        for line in text.split("\n"):

            stripped_line = line.strip()

            is_page_number = any(
                re.match(
                    pattern,
                    stripped_line,
                    flags=re.IGNORECASE,
                )
                for pattern in patterns
            )

            if not is_page_number:
                cleaned_lines.append(line)

        return "\n".join(cleaned_lines)

    @staticmethod
    def repair_hyphenated_line_breaks(text: str) -> str:
        """
        Repair English words broken across lines by PDF extraction.

        Example:

            applica-
            tion

        becomes:

            application

        This is deliberately limited to Latin alphabet words.
        It avoids changing legitimate hyphenated phrases where
        possible.
        """

        if not text:
            return ""

        pattern = re.compile(
            r"([A-Za-z]{2,})-\n([A-Za-z]{2,})"
        )

        return pattern.sub(
            r"\1\2",
            text,
        )

    @staticmethod
    def remove_excessive_blank_lines(text: str) -> str:
        """
        Replace three or more consecutive newlines with two.
        """

        if not text:
            return ""

        return re.sub(
            r"\n{3,}",
            "\n\n",
            text,
        )

    # ========================================================
    # Line Classification
    # ========================================================

    @staticmethod
    def is_bullet_line(line: str) -> bool:
        """
        Check whether a line appears to be a bullet/list item.
        """

        if not line:
            return False

        bullet_pattern = (
            r"^\s*("
            r"[-•●▪◦‣]"
            r"|"
            r"\d+[\.\)]"
            r"|"
            r"[A-Za-z][\.\)]"
            r")\s+"
        )

        return bool(
            re.match(
                bullet_pattern,
                line,
            )
        )

    @staticmethod
    def is_heading_like(line: str) -> bool:
        """
        Heuristic detection for headings.

        Examples:
            Eligibility
            Required Documents
            3. Application Process
            3.2 Address Update
        """

        line = line.strip()

        if not line:
            return False

        # Numbered section heading
        if re.match(
            r"^\d+(\.\d+)*[\.\)]?\s+\S+",
            line,
        ):
            return True

        # Short uppercase heading
        if (
            len(line) <= 100
            and line.isupper()
            and any(
                char.isalpha()
                for char in line
            )
        ):
            return True

        return False

    # ========================================================
    # Smart Line Joining
    # ========================================================

    def repair_broken_paragraphs(
        self,
        text: str,
    ) -> str:
        """
        Repair common PDF extraction line breaks.

        Example:

            The applicant must submit the required
            documents through the official portal.

        becomes:

            The applicant must submit the required documents
            through the official portal.

        The method tries to preserve:

        - Blank lines
        - Headings
        - Bullets
        - Numbered steps
        - List items
        """

        if not text:
            return ""

        lines = text.split("\n")

        output: List[str] = []

        paragraph_buffer: List[str] = []

        def flush_paragraph() -> None:

            if paragraph_buffer:

                paragraph = " ".join(
                    part.strip()
                    for part in paragraph_buffer
                    if part.strip()
                )

                if paragraph:
                    output.append(paragraph)

                paragraph_buffer.clear()

        for line in lines:

            stripped = line.strip()

            # Blank line means paragraph boundary
            if not stripped:

                flush_paragraph()

                if (
                    output
                    and output[-1] != ""
                ):
                    output.append("")

                continue

            # Preserve headings
            if self.is_heading_like(stripped):

                flush_paragraph()

                output.append(stripped)

                continue

            # Preserve bullets and numbered list items
            if self.is_bullet_line(stripped):

                flush_paragraph()

                output.append(stripped)

                continue

            # Add normal text to paragraph buffer
            paragraph_buffer.append(stripped)

            # Sentence-ending punctuation likely indicates
            # the end of a paragraph/sentence block.
            if re.search(
                r"[.!?।:;]$",
                stripped,
            ):
                flush_paragraph()

        flush_paragraph()

        # Remove duplicate blank lines
        cleaned_output = []

        for line in output:

            if (
                line == ""
                and cleaned_output
                and cleaned_output[-1] == ""
            ):
                continue

            cleaned_output.append(line)

        return "\n".join(
            cleaned_output
        )

    # ========================================================
    # Main Text Cleaning Pipeline
    # ========================================================

    def clean_text(
        self,
        text: Optional[str],
    ) -> str:
        """
        Run the complete text-cleaning pipeline.
        """

        if not text:
            return ""

        # 1. Normalize Unicode
        text = self.normalize_unicode(text)

        # 2. Normalize line endings
        text = self.normalize_line_endings(text)

        # 3. Remove unwanted control characters
        text = self.remove_control_characters(text)

        # 4. Repair words broken by hyphen + newline
        text = self.repair_hyphenated_line_breaks(text)

        # 5. Normalize spaces
        text = self.normalize_spaces(text)

        # 6. Remove standalone page-number lines
        text = self.remove_page_number_lines(text)

        # 7. Remove excessive blank lines
        text = self.remove_excessive_blank_lines(text)

        # 8. Repair PDF line-break issues
        text = self.repair_broken_paragraphs(text)

        # 9. Final whitespace cleanup
        text = self.remove_excessive_blank_lines(text)

        return text.strip()

    # ========================================================
    # Page Cleaning
    # ========================================================

    def clean_page(
        self,
        page: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Clean a single extracted PDF page.

        Existing page metadata is preserved.
        """

        cleaned_page = page.copy()

        original_text = page.get(
            "text",
            "",
        )

        original_character_count = len(
            original_text
        )

        # Do not attempt to invent text for OCR pages
        if not original_text.strip():

            cleaned_page["cleaned_text"] = ""

            cleaned_page[
                "original_character_count"
            ] = original_character_count

            cleaned_page[
                "cleaned_character_count"
            ] = 0

            cleaned_page[
                "cleaned_word_count"
            ] = 0

            cleaned_page[
                "text_changed"
            ] = False

            return cleaned_page

        cleaned_text = self.clean_text(
            original_text
        )

        cleaned_page[
            "cleaned_text"
        ] = cleaned_text

        cleaned_page[
            "original_character_count"
        ] = original_character_count

        cleaned_page[
            "cleaned_character_count"
        ] = len(cleaned_text)

        cleaned_page[
            "cleaned_word_count"
        ] = (
            len(cleaned_text.split())
            if cleaned_text
            else 0
        )

        cleaned_page[
            "text_changed"
        ] = (
            cleaned_text != original_text
        )

        return cleaned_page

    # ========================================================
    # Document Cleaning
    # ========================================================

    def clean_document(
        self,
        document_data: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Clean every page in one extracted PDF document.
        """

        document_id = document_data.get(
            "document_id",
            "unknown_document",
        )

        source_file = document_data.get(
            "source_file",
            "unknown.pdf",
        )

        logger.info(
            "Cleaning document: %s",
            source_file,
        )

        pages = document_data.get(
            "pages",
            [],
        )

        cleaned_pages: List[
            Dict[str, Any]
        ] = []

        total_original_characters = 0
        total_cleaned_characters = 0
        pages_with_text = 0
        empty_pages = 0
        pages_requiring_ocr = 0

        for page in pages:

            cleaned_page = self.clean_page(
                page
            )

            cleaned_pages.append(
                cleaned_page
            )

            original_count = cleaned_page.get(
                "original_character_count",
                0,
            )

            cleaned_count = cleaned_page.get(
                "cleaned_character_count",
                0,
            )

            total_original_characters += (
                original_count
            )

            total_cleaned_characters += (
                cleaned_count
            )

            if cleaned_count > 0:
                pages_with_text += 1
            else:
                empty_pages += 1

            if cleaned_page.get(
                "needs_ocr",
                False,
            ):
                pages_requiring_ocr += 1

        # Preserve original top-level metadata
        cleaned_document = (
            document_data.copy()
        )

        cleaned_document[
            "pages"
        ] = cleaned_pages

        cleaned_document[
            "cleaning_info"
        ] = {
            "cleaner": "TextCleaner",
            "cleaned_at": datetime.now(
                timezone.utc
            ).isoformat(),
            "cleaning_version": "1.0",
        }

        cleaned_document[
            "cleaning_summary"
        ] = {
            "document_id": document_id,
            "total_pages": len(
                cleaned_pages
            ),
            "pages_with_cleaned_text": (
                pages_with_text
            ),
            "empty_pages": empty_pages,
            "pages_requiring_ocr": (
                pages_requiring_ocr
            ),
            "original_character_count": (
                total_original_characters
            ),
            "cleaned_character_count": (
                total_cleaned_characters
            ),
            "characters_removed": max(
                0,
                total_original_characters
                - total_cleaned_characters,
            ),
        }

        logger.info(
            "Cleaned %s | Pages: %d | "
            "Original chars: %d | "
            "Cleaned chars: %d",
            source_file,
            len(cleaned_pages),
            total_original_characters,
            total_cleaned_characters,
        )

        return cleaned_document

    # ========================================================
    # Load JSON
    # ========================================================

    @staticmethod
    def load_document(
        json_path: Path,
    ) -> Dict[str, Any]:
        """
        Load extracted JSON document.
        """

        with json_path.open(
            "r",
            encoding="utf-8",
        ) as file:

            return json.load(file)

    # ========================================================
    # Save Cleaned Document
    # ========================================================

    def save_cleaned_document(
        self,
        document_data: Dict[str, Any],
    ) -> Path:
        """
        Save cleaned document as JSON.
        """

        document_id = document_data.get(
            "document_id"
        )

        if not document_id:

            raise ValueError(
                "Document is missing document_id."
            )

        output_path = (
            self.output_dir
            / f"{document_id}.json"
        )

        with output_path.open(
            "w",
            encoding="utf-8",
        ) as file:

            json.dump(
                document_data,
                file,
                ensure_ascii=False,
                indent=2,
            )

        logger.info(
            "Saved cleaned document: %s",
            output_path,
        )

        return output_path

    # ========================================================
    # Process Single JSON File
    # ========================================================

    def process_single_file(
        self,
        json_path: Path,
    ) -> Dict[str, Any]:
        """
        Load, clean, and save one extracted JSON file.
        """

        logger.info(
            "Processing extracted file: %s",
            json_path.name,
        )

        document_data = self.load_document(
            json_path
        )

        cleaned_document = (
            self.clean_document(
                document_data
            )
        )

        output_path = (
            self.save_cleaned_document(
                cleaned_document
            )
        )

        summary = cleaned_document.get(
            "cleaning_summary",
            {},
        )

        return {
            "source_file": (
                cleaned_document.get(
                    "source_file",
                    json_path.name,
                )
            ),
            "status": "success",
            "output_file": str(
                output_path
            ),
            "total_pages": summary.get(
                "total_pages",
                0,
            ),
            "pages_with_text": (
                summary.get(
                    "pages_with_cleaned_text",
                    0,
                )
            ),
            "empty_pages": summary.get(
                "empty_pages",
                0,
            ),
        }

    # ========================================================
    # Process All Extracted Files
    # ========================================================

    def process_all_documents(
        self,
    ) -> Dict[str, Any]:
        """
        Clean all JSON files inside data/extracted/.
        """

        json_files = self.find_json_files()

        if not json_files:

            logger.warning(
                "No extracted JSON files found in: %s",
                self.input_dir,
            )

            return {
                "total_files": 0,
                "successful_files": 0,
                "failed_files": 0,
                "results": [],
            }

        results: List[
            Dict[str, Any]
        ] = []

        successful_files = 0
        failed_files = 0

        logger.info(
            "Starting text cleaning for "
            "%d document(s)",
            len(json_files),
        )

        for json_path in json_files:

            try:

                result = (
                    self.process_single_file(
                        json_path
                    )
                )

                results.append(result)

                successful_files += 1

            except Exception as error:

                failed_files += 1

                logger.exception(
                    "Failed to clean %s: %s",
                    json_path.name,
                    error,
                )

                results.append(
                    {
                        "source_file": (
                            json_path.name
                        ),
                        "status": "failed",
                        "error": str(error),
                    }
                )

        summary = {
            "total_files": len(
                json_files
            ),
            "successful_files": (
                successful_files
            ),
            "failed_files": (
                failed_files
            ),
            "results": results,
        }

        logger.info("=" * 60)
        logger.info(
            "TEXT CLEANING COMPLETED"
        )
        logger.info("=" * 60)
        logger.info(
            "Total documents: %d",
            len(json_files),
        )
        logger.info(
            "Successful: %d",
            successful_files,
        )
        logger.info(
            "Failed: %d",
            failed_files,
        )
        logger.info("=" * 60)

        return summary


# ============================================================
# Main
# ============================================================

def main() -> None:
    """
    Run text cleaning directly.
    """

    print(
        "\n"
        + "=" * 60
    )

    print(
        "PDS & SOCIAL WELFARE AI - TEXT CLEANING"
    )

    print(
        "=" * 60
    )

    cleaner = TextCleaner()

    summary = (
        cleaner.process_all_documents()
    )

    print(
        "\nCleaning Summary"
    )

    print(
        "-" * 60
    )

    print(
        f"Total documents : "
        f"{summary['total_files']}"
    )

    print(
        f"Successful      : "
        f"{summary['successful_files']}"
    )

    print(
        f"Failed          : "
        f"{summary['failed_files']}"
    )

    if summary["results"]:

        print(
            "\nProcessed Files"
        )

        print(
            "-" * 60
        )

        for result in summary[
            "results"
        ]:

            if (
                result["status"]
                == "success"
            ):

                print(
                    f"[OK] "
                    f"{result['source_file']} "
                    f"| Pages: "
                    f"{result['total_pages']} "
                    f"| Text pages: "
                    f"{result['pages_with_text']} "
                    f"| Empty: "
                    f"{result['empty_pages']}"
                )

            else:

                print(
                    f"[FAILED] "
                    f"{result['source_file']} "
                    f"| Error: "
                    f"{result['error']}"
                )

    print(
        "\nCleaned JSON directory:"
    )

    print(
        CLEANED_DIR
    )

    print(
        "\n"
        + "=" * 60
    )


if __name__ == "__main__":
    main()

