"""
rag_pipeline.py

Main Retrieval-Augmented Generation (RAG) pipeline for JanMitra.

Pipeline:

User Question
    ->
QueryProcessor
    ->
Retriever
    ->
ContextBuilder
    ->
PromptBuilder
    ->
LLMClient
    ->
Groq API
    ->
Final Answer + Sources

This module orchestrates the complete query-time RAG workflow.

It does NOT handle:
- PDF extraction
- Text cleaning
- Chunk creation
- Document embedding
- ChromaDB ingestion

Those operations belong to the ingestion pipeline.
"""

from __future__ import annotations

import hashlib
import json
import logging
import re
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

import fitz


# ============================================================
# Project Imports
# ============================================================

from retrieval.query_processor import QueryProcessor
from retrieval.context_builder import ContextBuilder, BuiltContext
from retrieval.retriever import MultilingualRetriever

from rag.prompt_builder import PromptBuilder

from llm.llm_client import (
    LLMClient,
    LLMClientError,
)


# ============================================================
# Logging
# ============================================================

logger = logging.getLogger(__name__)


# ============================================================
# Custom Exceptions
# ============================================================

class RAGPipelineError(Exception):
    """
    Base exception for all RAG pipeline errors.
    """


class QueryProcessingError(RAGPipelineError):
    """
    Raised when query processing fails.
    """


class RetrievalError(RAGPipelineError):
    """
    Raised when document retrieval fails.
    """


class ContextBuildingError(RAGPipelineError):
    """
    Raised when context construction fails.
    """


class PromptBuildingError(RAGPipelineError):
    """
    Raised when prompt construction fails.
    """


class AnswerGenerationError(RAGPipelineError):
    """
    Raised when LLM answer generation fails.
    """


# ============================================================
# RAG Response Model
# ============================================================

@dataclass
class RAGResponse:
    """
    Final response returned by JanMitra's RAG pipeline.

    Attributes:
        question:
            Original citizen question.

        answer:
            Final LLM-generated answer.

        sources:
            Government document sources used in context.

        processed_query:
            Normalized query generated by QueryProcessor.

        retrieval_query:
            Query actually used for vector search.

        detected_language:
            Detected query language.

        query_type:
            Detected query intent.

        retrieved_chunks:
            Number of chunks returned by Retriever.

        context_chunks:
            Number of chunks actually sent to the LLM.

        context_truncated:
            Whether ContextBuilder truncated retrieved context.

        processing_time:
            Total execution time in seconds.

        retrieved_images:
            At most one strongest visual tied to indexed metadata or the
            highest-ranked source page.

        metadata:
            Additional diagnostic information.
    """

    question: str

    answer: str

    sources: List[Dict[str, Any]]

    processed_query: str

    retrieval_query: str

    detected_language: str

    query_type: str

    retrieved_chunks: int

    context_chunks: int

    context_truncated: bool

    processing_time: float

    retrieved_images: List[Dict[str, Any]] = field(
        default_factory=list
    )

    metadata: Dict[str, Any] = field(
        default_factory=dict
    )

    def to_dict(
        self,
    ) -> Dict[str, Any]:
        """
        Convert response into a dictionary.

        Useful for FastAPI JSON responses.
        """

        return asdict(self)


# ============================================================
# RAG Pipeline
# ============================================================

class RAGPipeline:
    """
    Main JanMitra RAG pipeline.

    Example:

        pipeline = RAGPipeline()

        response = pipeline.query(
            "What are the eligibility conditions?"
        )

        print(response.answer)

        for source in response.sources:
            print(source)
    """

    def __init__(
        self,
        query_processor: Optional[
            QueryProcessor
        ] = None,
        retriever: Optional[
            MultilingualRetriever
        ] = None,
        context_builder: Optional[
            ContextBuilder
        ] = None,
        prompt_builder: Optional[
            PromptBuilder
        ] = None,
        llm_client: Optional[
            LLMClient
        ] = None,
        top_k: int = 5,
    ) -> None:
        """
        Initialize all RAG components.

        Dependencies can optionally be injected for testing.

        Args:
            query_processor:
                QueryProcessor instance.

            retriever:
                Retriever instance.

            context_builder:
                ContextBuilder instance.

            prompt_builder:
                PromptBuilder instance.

            llm_client:
                Groq LLMClient instance.

            top_k:
                Default number of document chunks to retrieve.
        """

        if top_k <= 0:

            raise ValueError(
                "top_k must be greater than 0."
            )

        self.top_k = top_k

        logger.info(
            "Initializing JanMitra RAG pipeline..."
        )

        # ----------------------------------------------------
        # Query Processor
        # ----------------------------------------------------

        try:

            self.query_processor = (
                query_processor
                or QueryProcessor()
            )

            logger.info(
                "QueryProcessor initialized."
            )

        except Exception as exc:

            logger.exception(
                "Failed to initialize QueryProcessor."
            )

            raise RAGPipelineError(
                f"Failed to initialize "
                f"QueryProcessor: {exc}"
            ) from exc

        # ----------------------------------------------------
        # Retriever
        # ----------------------------------------------------

        try:

            self.retriever = (
                retriever
                or MultilingualRetriever()
            )

            logger.info(
                "Retriever initialized."
            )

        except Exception as exc:

            logger.exception(
                "Failed to initialize Retriever."
            )

            raise RAGPipelineError(
                f"Failed to initialize "
                f"Retriever: {exc}"
            ) from exc

        # ----------------------------------------------------
        # Context Builder
        # ----------------------------------------------------

        try:

            self.context_builder = (
                context_builder
                or ContextBuilder(
                    max_chunks=top_k
                )
            )

            logger.info(
                "ContextBuilder initialized."
            )

        except Exception as exc:

            logger.exception(
                "Failed to initialize ContextBuilder."
            )

            raise RAGPipelineError(
                f"Failed to initialize "
                f"ContextBuilder: {exc}"
            ) from exc

        # ----------------------------------------------------
        # Prompt Builder
        # ----------------------------------------------------

        try:

            self.prompt_builder = (
                prompt_builder
                or PromptBuilder()
            )

            logger.info(
                "PromptBuilder initialized."
            )

        except Exception as exc:

            logger.exception(
                "Failed to initialize PromptBuilder."
            )

            raise RAGPipelineError(
                f"Failed to initialize "
                f"PromptBuilder: {exc}"
            ) from exc

        # ----------------------------------------------------
        # LLM Client
        # ----------------------------------------------------

        try:

            self.llm_client = (
                llm_client
                or LLMClient()
            )

            logger.info(
                "LLMClient initialized."
            )

        except Exception as exc:

            logger.exception(
                "Failed to initialize LLMClient."
            )

            raise RAGPipelineError(
                f"Failed to initialize "
                f"LLMClient: {exc}"
            ) from exc

        logger.info(
            "JanMitra RAG pipeline "
            "initialized successfully."
        )

    # ========================================================
    # Main Query Method
    # ========================================================

    def query(
        self,
        question: str,
        top_k: Optional[int] = None,
    ) -> RAGResponse:
        """
        Run the complete JanMitra RAG pipeline.

        Flow:

        1. Validate question
        2. Process query
        3. Retrieve relevant chunks
        4. Build context
        5. Build LLM prompts
        6. Generate answer with Groq
        7. Prepare source citations
        8. Return structured response

        Args:
            question:
                Citizen question.

            top_k:
                Optional number of retrieval results.

        Returns:
            RAGResponse
        """

        start_time = (
            time.perf_counter()
        )

        # ----------------------------------------------------
        # Validate Question
        # ----------------------------------------------------

        if not isinstance(
            question,
            str,
        ):

            raise TypeError(
                "question must be a string."
            )

        question = (
            question.strip()
        )

        if not question:

            raise ValueError(
                "question cannot be empty."
            )

        retrieval_top_k = (
            top_k
            if top_k is not None
            else self.top_k
        )

        if retrieval_top_k <= 0:

            raise ValueError(
                "top_k must be greater than 0."
            )

        logger.info(
            "Starting RAG query."
        )

        # ====================================================
        # STEP 1: Process Query
        # ====================================================

        try:

            processed = (
                self.query_processor.process(
                    question
                )
            )

        except Exception as exc:

            logger.exception(
                "Query processing failed."
            )

            raise QueryProcessingError(
                f"Failed to process query: {exc}"
            ) from exc

        # ----------------------------------------------------
        # Extract Processed Query Attributes Safely
        # ----------------------------------------------------

        normalized_query = getattr(
            processed,
            "normalized_query",
            question,
        )

        retrieval_query = getattr(
            processed,
            "retrieval_query",
            normalized_query,
        )

        detected_language = getattr(
            processed,
            "detected_language",
            "english",
        )

        query_type = getattr(
            processed,
            "query_type",
            "general",
        )

        keywords = getattr(
            processed,
            "keywords",
            [],
        )

        expanded_terms = getattr(
            processed,
            "expanded_terms",
            [],
        )

        logger.info(
            "Query processed | "
            "language=%s | "
            "type=%s",
            detected_language,
            query_type,
        )

        # ====================================================
        # STEP 2: Retrieve Relevant Document Chunks
        # ====================================================

        try:

            retrieved_results = (
                self._retrieve(
                    query=retrieval_query,
                    top_k=retrieval_top_k,
                )
            )

        except Exception as exc:

            logger.exception(
                "Document retrieval failed."
            )

            raise RetrievalError(
                f"Failed to retrieve "
                f"documents: {exc}"
            ) from exc

        # Ensure results are always list-like.

        if retrieved_results is None:

            retrieved_results = []

        try:

            retrieved_count = len(
                retrieved_results
            )

        except TypeError:

            retrieved_results = list(
                retrieved_results
            )

            retrieved_count = len(
                retrieved_results
            )

        logger.info(
            "Retrieval complete | "
            "chunks=%d",
            retrieved_count,
        )

        # ====================================================
        # STEP 3: Handle No Retrieval Results
        # ====================================================

        if not retrieved_results:

            processing_time = (
                time.perf_counter()
                - start_time
            )

            return RAGResponse(

                question=question,

                answer=(
                    self._no_information_answer(
                        detected_language
                    )
                ),

                sources=[],

                processed_query=(
                    normalized_query
                ),

                retrieval_query=(
                    retrieval_query
                ),

                detected_language=(
                    detected_language
                ),

                query_type=(
                    query_type
                ),

                retrieved_chunks=0,

                context_chunks=0,

                context_truncated=False,

                processing_time=round(
                    processing_time,
                    4,
                ),

                metadata={
                    "status":
                        "no_retrieval_results",

                    "keywords":
                        keywords,

                    "expanded_terms":
                        expanded_terms,

                    "top_k":
                        retrieval_top_k,
                },
            )

        # ====================================================
        # STEP 4: Build LLM Context
        # ====================================================

        try:

            built_context = (
                self.context_builder.build(
                    retrieved_results
                )
            )

        except Exception as exc:

            logger.exception(
                "Context building failed."
            )

            raise ContextBuildingError(
                f"Failed to build "
                f"context: {exc}"
            ) from exc

        logger.info(
            "Context built | "
            "chunks=%d | "
            "characters=%d",
            built_context.total_chunks,
            built_context.total_characters,
        )

        # ====================================================
        # STEP 5: Handle Empty Context
        # ====================================================

        if (
            not built_context.context
            or not built_context.context.strip()
        ):

            processing_time = (
                time.perf_counter()
                - start_time
            )

            return RAGResponse(

                question=question,

                answer=(
                    self._no_information_answer(
                        detected_language
                    )
                ),

                sources=[],

                processed_query=(
                    normalized_query
                ),

                retrieval_query=(
                    retrieval_query
                ),

                detected_language=(
                    detected_language
                ),

                query_type=(
                    query_type
                ),

                retrieved_chunks=(
                    retrieved_count
                ),

                context_chunks=0,

                context_truncated=(
                    built_context.truncated
                ),

                processing_time=round(
                    processing_time,
                    4,
                ),

                metadata={
                    "status":
                        "empty_context",

                    "keywords":
                        keywords,

                    "expanded_terms":
                        expanded_terms,

                    "top_k":
                        retrieval_top_k,
                },
            )

        # ====================================================
        # STEP 6: Build Prompt
        # ====================================================

        try:

            built_prompt = (
                self.prompt_builder.build(

                    question=question,

                    context=(
                        built_context.context
                    ),

                    language=(
                        detected_language
                    ),

                    query_type=(
                        query_type
                    ),
                )
            )

        except Exception as exc:

            logger.exception(
                "Prompt building failed."
            )

            raise PromptBuildingError(
                f"Failed to build "
                f"LLM prompt: {exc}"
            ) from exc

        logger.info(
            "LLM prompt built successfully."
        )

        # ====================================================
        # STEP 7: Generate Answer Using Groq
        # ====================================================

        try:

            answer = (
                self.llm_client.generate(
                    prompt=(
                        built_prompt.user_prompt
                    ),
                    system_prompt=(
                        built_prompt.system_prompt
                    ),
                    temperature=0.1,
                    max_tokens=1000,
                )
            )

        except LLMClientError as exc:

            logger.exception(
                "LLM answer generation failed."
            )

            raise AnswerGenerationError(
                f"Failed to generate "
                f"answer: {exc}"
            ) from exc

        except Exception as exc:

            logger.exception(
                "Unexpected LLM generation error."
            )

            raise AnswerGenerationError(
                f"Unexpected answer "
                f"generation error: {exc}"
            ) from exc

        # ====================================================
        # STEP 8: Prepare Sources
        # ====================================================

        sources = (
            self._prepare_sources(
                built_context
            )
        )

        # Visual evidence is optional. A missing or malformed visual must not
        # make an otherwise grounded text answer fail.
        try:
            retrieved_images = self._prepare_retrieved_images(
                retrieval_query,
                retrieved_results,
            )
        except Exception:
            logger.exception(
                "Visual retrieval failed; returning the grounded text answer."
            )
            retrieved_images = []

        # ====================================================
        # STEP 9: Build Final Response
        # ====================================================

        processing_time = (
            time.perf_counter()
            - start_time
        )

        response = RAGResponse(

            question=question,

            answer=answer,

            sources=sources,

            retrieved_images=retrieved_images,

            processed_query=(
                normalized_query
            ),

            retrieval_query=(
                retrieval_query
            ),

            detected_language=(
                detected_language
            ),

            query_type=(
                query_type
            ),

            retrieved_chunks=(
                retrieved_count
            ),

            context_chunks=(
                built_context.total_chunks
            ),

            context_truncated=(
                built_context.truncated
            ),

            processing_time=round(
                processing_time,
                4,
            ),

            metadata={
                "status":
                    "success",

                "keywords":
                    keywords,

                "expanded_terms":
                    expanded_terms,

                "context_characters":
                    built_context
                    .total_characters,

                "top_k":
                    retrieval_top_k,

                "llm_provider":
                    "groq",

                "llm_model":
                    getattr(
                        self.llm_client,
                        "model",
                        None,
                    ),
            },
        )

        logger.info(
            "RAG query completed | "
            "retrieved=%d | "
            "context=%d | "
            "time=%.4fs",
            retrieved_count,
            built_context.total_chunks,
            processing_time,
        )

        return response

    # ========================================================
    # Retrieval Adapter
    # ========================================================

    def _retrieve(
        self,
        query: str,
        top_k: int,
    ) -> List[Any]:
        """
        Execute semantic retrieval.

        Preferred Retriever interface:

            retriever.retrieve(
                query=query,
                top_k=top_k
            )

        Also supports:

            retriever.search(...)
        """

        # ----------------------------------------------------
        # Preferred retrieve() method
        # ----------------------------------------------------

        if hasattr(
            self.retriever,
            "retrieve",
        ):

            try:

                results = (
                    self.retriever.retrieve(
                        query=query,
                        top_k=top_k,
                    )
                )

            except TypeError:

                results = (
                    self.retriever.retrieve(
                        query,
                        top_k,
                    )
                )

            return (
                results
                if results is not None
                else []
            )

        # ----------------------------------------------------
        # Alternative search() method
        # ----------------------------------------------------

        if hasattr(
            self.retriever,
            "search",
        ):

            try:

                results = (
                    self.retriever.search(
                        query=query,
                        top_k=top_k,
                    )
                )

            except TypeError:

                results = (
                    self.retriever.search(
                        query,
                        top_k,
                    )
                )

            return (
                results
                if results is not None
                else []
            )

        raise AttributeError(
            "Retriever must implement "
            "either retrieve() or search()."
        )

    # ========================================================
    # Prepare Visual Evidence
    # ========================================================

    @classmethod
    def _prepare_retrieved_images(
        cls,
        query: str,
        results: List[Any],
        data_dir: Optional[Path] = None,
        output_dir: Optional[Path] = None,
    ) -> List[Dict[str, Any]]:
        """Return only the strongest relevant image/chart/graph.

        Captioned preprocessing records are preferred. If this checkout has
        not indexed visual records yet, the highest-ranked text source and
        page are used to crop the query-matching visual from the source PDF.
        """

        backend_dir = Path(__file__).resolve().parent.parent
        data_dir = Path(data_dir) if data_dir else backend_dir / "data"
        output_dir = (
            Path(output_dir)
            if output_dir
            else data_dir / "retrieved_visuals"
        )
        normalized_results = [
            result for result in results if isinstance(result, dict)
        ]

        indexed = cls._best_indexed_visual(
            query,
            normalized_results,
            data_dir,
        )
        if indexed is not None:
            return [indexed]

        for result in normalized_results:
            fallback = cls._crop_source_page_visual(
                query,
                result,
                data_dir,
                output_dir,
            )
            if fallback is not None:
                return [fallback]

        return []

    @classmethod
    def _best_indexed_visual(
        cls,
        query: str,
        results: List[Dict[str, Any]],
        data_dir: Path,
    ) -> Optional[Dict[str, Any]]:
        """Rank visual records represented in preprocessing corpus metadata."""

        query_tokens = cls._meaningful_tokens(query)
        if len(query_tokens) < 2:
            return None

        source_pages = {
            (
                cls._source_file(result.get("metadata") or {}),
                cls._page_number(result.get("metadata") or {}),
            )
            for result in results
        }
        best: Optional[Dict[str, Any]] = None
        best_score = 0.0
        corpus_paths = sorted(data_dir.glob("**/corpus.jsonl"))

        for corpus_path in corpus_paths:
            try:
                lines = corpus_path.read_text(encoding="utf-8").splitlines()
            except OSError:
                logger.warning("Could not read visual corpus: %s", corpus_path)
                continue

            for line in lines:
                try:
                    record = json.loads(line)
                except (json.JSONDecodeError, TypeError):
                    continue
                if not isinstance(record, dict):
                    continue

                metadata = record.get("metadata") or {}
                if not isinstance(metadata, dict):
                    metadata = {}
                layout = str(
                    record.get("layout")
                    or metadata.get("layout")
                    or ""
                ).casefold()
                image_value = (
                    record.get("image_path")
                    or metadata.get("image_path")
                    or metadata.get("preview_path")
                )
                if layout not in {
                    "image", "chart", "graph", "diagram", "figure", "picture",
                } or not image_value:
                    continue

                image_path = cls._resolve_image_path(image_value, data_dir)
                if image_path is None:
                    continue

                searchable = " ".join(
                    str(value or "")
                    for value in (
                        record.get("text"),
                        record.get("title"),
                        metadata.get("title"),
                        metadata.get("caption"),
                        metadata.get("parent_section"),
                    )
                )
                matched = query_tokens & cls._meaningful_tokens(searchable)
                if len(matched) < 2:
                    continue

                coverage = len(matched) / len(query_tokens)
                source_file = (
                    cls._source_file(record)
                    or cls._source_file(metadata)
                )
                page_number = (
                    cls._page_number(record)
                    or cls._page_number(metadata)
                )
                source_bonus = (
                    0.20
                    if (source_file, page_number) in source_pages
                    else 0.0
                )
                score = min(1.0, coverage + source_bonus)
                if coverage < 0.40 or score <= best_score:
                    continue

                best_score = score
                best = {
                    "image_path": str(image_path),
                    "layout": layout,
                    "coordinates": (
                        record.get("coordinates")
                        or metadata.get("coordinates")
                        or {}
                    ),
                    "source_file": source_file,
                    "page_number": page_number,
                    "chunk_id": (
                        record.get("chunk_id")
                        or metadata.get("chunk_id")
                    ),
                    "title": (
                        record.get("title")
                        or metadata.get("title")
                        or searchable[:180]
                    ),
                    "score": round(score, 4),
                    "selection_method": "indexed_visual_metadata",
                }

        return best

    @classmethod
    def _crop_source_page_visual(
        cls,
        query: str,
        result: Dict[str, Any],
        data_dir: Path,
        output_dir: Path,
    ) -> Optional[Dict[str, Any]]:
        """Crop the matching chart region from a retrieved source PDF page."""

        metadata = result.get("metadata") or {}
        if not isinstance(metadata, dict):
            return None
        source_file = cls._source_file(metadata)
        page_number = cls._page_number(metadata)
        if not source_file or page_number is None:
            return None

        source_path = cls._resolve_source_pdf(metadata, data_dir, source_file)
        if source_path is None:
            return None

        query_tokens = cls._meaningful_tokens(query)
        if len(query_tokens) < 2:
            return None

        with fitz.open(source_path) as document:
            if page_number < 1 or page_number > document.page_count:
                return None
            page = document.load_page(page_number - 1)
            blocks = page.get_text("blocks")

            title_block: Optional[tuple[Any, ...]] = None
            title_score = 0.0
            for block in blocks:
                text = str(block[4] or "")
                block_tokens = cls._meaningful_tokens(text)
                matched = query_tokens & block_tokens
                coverage = len(matched) / len(query_tokens)
                if len(matched) >= 2 and coverage > title_score:
                    title_score = coverage
                    title_block = block

            if title_block is None or title_score < 0.40:
                return None

            title_y0 = float(title_block[1])
            title_y1 = float(title_block[3])
            source_blocks = [
                block
                for block in blocks
                if float(block[1]) > title_y1
                and str(block[4] or "").lstrip().casefold().startswith("source:")
            ]
            source_block = (
                min(source_blocks, key=lambda block: float(block[1]))
                if source_blocks
                else None
            )

            x0 = max(page.rect.x0, float(title_block[0]) - 12)
            x1 = min(page.rect.x1, float(title_block[2]) + 12)
            y0 = max(page.rect.y0, title_y0 - 12)
            if source_block is not None:
                x0 = max(page.rect.x0, min(x0, float(source_block[0]) - 8))
                x1 = min(page.rect.x1, max(x1, float(source_block[2]) + 8))
                y1 = min(page.rect.y1, float(source_block[3]) + 6)
            else:
                y1 = min(page.rect.y1, title_y1 + page.rect.height * 0.32)

            clip = fitz.Rect(x0, y0, x1, y1) & page.rect
            if clip.is_empty or clip.width < 80 or clip.height < 80:
                return None

            digest = hashlib.sha256(
                f"{source_file}|{page_number}|{query.casefold()}".encode("utf-8")
            ).hexdigest()[:10]
            safe_stem = re.sub(
                r"[^A-Za-z0-9._-]+",
                "_",
                Path(source_file).stem,
            ).strip("._") or "document"
            output_dir.mkdir(parents=True, exist_ok=True)
            output_path = (
                output_dir
                / f"{safe_stem}_p{page_number:04d}_{digest}.png"
            )
            if not output_path.is_file() or output_path.stat().st_size == 0:
                pixmap = page.get_pixmap(
                    matrix=fitz.Matrix(2, 2),
                    clip=clip,
                    alpha=False,
                )
                pixmap.save(output_path)

        score_value = result.get("similarity")
        if score_value is None:
            distance = result.get("distance")
            try:
                score_value = 1.0 - float(distance)
            except (TypeError, ValueError):
                score_value = title_score

        return {
            "image_path": str(output_path.resolve()),
            "layout": "chart",
            "coordinates": {
                "x1": round(clip.x0, 2),
                "y1": round(clip.y0, 2),
                "x2": round(clip.x1, 2),
                "y2": round(clip.y1, 2),
            },
            "source_file": source_file,
            "page_number": page_number,
            "chunk_id": (
                result.get("chunk_id")
                or metadata.get("chunk_id")
            ),
            "title": " ".join(str(title_block[4]).split()),
            "score": round(float(score_value or 0.0), 4),
            "selection_method": "retrieved_source_page_crop",
        }

    @staticmethod
    def _meaningful_tokens(value: Any) -> set[str]:
        stop_words = {
            "about", "after", "also", "and", "are", "been", "for", "from",
            "has", "have", "how", "into", "its", "of", "on", "the", "this",
            "to", "was", "were", "what", "when", "where", "which", "with",
        }
        return {
            token
            for token in re.findall(r"[A-Za-z0-9]+", str(value).casefold())
            if len(token) >= 2 and token not in stop_words
        }

    @staticmethod
    def _source_file(metadata: Dict[str, Any]) -> Optional[str]:
        value = (
            metadata.get("source_file")
            or metadata.get("file_name")
            or metadata.get("source")
        )
        if not value:
            return None
        return Path(str(value).replace("\\", "/")).name

    @staticmethod
    def _page_number(metadata: Dict[str, Any]) -> Optional[int]:
        value = metadata.get("page_number") or metadata.get("page")
        try:
            number = int(value)
            return number if number >= 1 else None
        except (TypeError, ValueError):
            return None

    @staticmethod
    def _resolve_source_pdf(
        metadata: Dict[str, Any],
        data_dir: Path,
        source_file: str,
    ) -> Optional[Path]:
        source_value = metadata.get("source")
        if source_value:
            candidate = Path(str(source_value))
            if candidate.is_file():
                return candidate.resolve()
        candidate = data_dir / "raw" / source_file
        return candidate.resolve() if candidate.is_file() else None

    @staticmethod
    def _resolve_image_path(
        value: Any,
        data_dir: Path,
    ) -> Optional[Path]:
        candidate = Path(str(value))
        if candidate.is_file():
            return candidate.resolve()
        normalized = str(value).replace("\\", "/")
        marker = "/data/images/"
        lowered = normalized.casefold()
        index = lowered.find(marker)
        if index >= 0:
            relative = normalized[index + len("/data/"):]
            candidate = data_dir / Path(relative)
            if candidate.is_file():
                return candidate.resolve()
        return None

    # ========================================================
    # Prepare Sources
    # ========================================================

    @staticmethod
    def _prepare_sources(
        built_context: BuiltContext,
    ) -> List[Dict[str, Any]]:
        """
        Convert ContextBuilder sources into API-friendly
        dictionaries.

        Duplicate source references are removed.
        """

        sources: List[
            Dict[str, Any]
        ] = []

        seen = set()

        for source in (
            built_context.sources
        ):

            source_key = (

                source.file_name,

                source.page_number,

                source.chunk_id,
            )

            if source_key in seen:

                continue

            seen.add(
                source_key
            )

            sources.append(
                {
                    "source_id":
                        source.source_id,

                    "file_name":
                        source.file_name,

                    "page_number":
                        source.page_number,

                    "chunk_id":
                        source.chunk_id,

                    "document_id":
                        source.document_id,

                    "score":
                        source.score,

                    "distance":
                        source.distance,
                }
            )

        return sources

    # ========================================================
    # No Information Answer
    # ========================================================

    @staticmethod
    def _no_information_answer(
        language: str,
    ) -> str:
        """
        Return a localized fallback when retrieval fails.
        """

        normalized_language = (
            language
            or "english"
        ).lower()

        if normalized_language == "hindi":

            return (
                "उपलब्ध सरकारी दस्तावेज़ों में "
                "इस प्रश्न का उत्तर देने के लिए "
                "पर्याप्त जानकारी नहीं मिली।"
            )

        if normalized_language in {
            "hinglish",
            "mixed",
        }:

            return (
                "Available government documents mein "
                "is question ka answer dene ke liye "
                "sufficient information nahi mili."
            )

        return (
            "I could not find sufficient information "
            "in the available government documents "
            "to answer this question."
        )


# ============================================================
# Manual Test
# ============================================================

def main() -> None:
    """
    Interactive test for the complete JanMitra RAG pipeline.

    Before running:

    1. Government PDFs must already be processed.
    2. Chunks must already be embedded.
    3. Embeddings must already be stored in ChromaDB.
    4. backend/.env must contain GROQ_API_KEY.

    Run from backend directory:

        python -m rag.rag_pipeline
    """

    logging.basicConfig(
        level=logging.INFO,
        format=(
            "%(asctime)s | "
            "%(levelname)s | "
            "%(message)s"
        ),
    )

    print(
        "\n"
        + "=" * 60
    )

    print(
        "JANMITRA - COMPLETE RAG PIPELINE"
    )

    print(
        "=" * 60
    )

    # --------------------------------------------------------
    # Initialize Pipeline
    # --------------------------------------------------------

    try:

        pipeline = (
            RAGPipeline(
                top_k=5
            )
        )

    except Exception as exc:

        print(
            "\nFailed to initialize "
            "RAG pipeline:"
        )

        print(
            exc
        )

        return

    # --------------------------------------------------------
    # Display Configuration
    # --------------------------------------------------------

    print(
        "\nPipeline initialized successfully."
    )

    print(
        f"LLM Provider: Groq"
    )

    print(
    f"LLM Model: "
    f"{getattr(pipeline.llm_client, 'model', 'Unknown')}"
)

    print(
        f"Retrieval Top-K: "
        f"{pipeline.top_k}"
    )

    print(
        "\nAsk a question about the "
        "indexed government documents."
    )

    print(
        "Type 'exit' to stop."
    )

    # --------------------------------------------------------
    # Interactive Query Loop
    # --------------------------------------------------------

    while True:

        try:

            question = input(
                "\nYour question: "
            ).strip()

        except (
            KeyboardInterrupt,
            EOFError,
        ):

            print(
                "\nExiting JanMitra..."
            )

            break

        if question.lower() in {
            "exit",
            "quit",
            "q",
        }:

            print(
                "\nExiting JanMitra..."
            )

            break

        if not question:

            continue

        print(
            "\nSearching government "
            "documents..."
        )

        # ----------------------------------------------------
        # Execute Pipeline
        # ----------------------------------------------------

        try:

            response = (
                pipeline.query(
                    question
                )
            )

        except RAGPipelineError as exc:

            print(
                "\nRAG Pipeline Error:"
            )

            print(
                exc
            )

            continue

        except Exception as exc:

            logger.exception(
                "Unexpected pipeline error."
            )

            print(
                "\nUnexpected Error:"
            )

            print(
                exc
            )

            continue

        # ----------------------------------------------------
        # Display Answer
        # ----------------------------------------------------

        print(
            "\n"
            + "=" * 60
        )

        print(
            "ANSWER"
        )

        print(
            "=" * 60
        )

        print(
            response.answer
        )

        # ----------------------------------------------------
        # Display Sources
        # ----------------------------------------------------

        print(
            "\n"
            + "=" * 60
        )

        print(
            "SOURCES"
        )

        print(
            "=" * 60
        )

        if not response.sources:

            print(
                "No sources available."
            )

        else:

            for index, source in enumerate(
                response.sources,
                start=1,
            ):

                print(
    f"\n{index}. "
    f"{source.get('file_name', 'Unknown document')}"
)

                page_number = (
                    source.get(
                        "page_number"
                    )
                )

                if page_number is not None:

                    print(
                        f"   Page: "
                        f"{page_number}"
                    )

                score = (
                    source.get(
                        "score"
                    )
                )

                if score is not None:

                    try:

                        print(
                            f"   Score: "
                            f"{float(score):.4f}"
                        )

                    except (
                        TypeError,
                        ValueError,
                    ):

                        pass

                distance = (
                    source.get(
                        "distance"
                    )
                )

                if distance is not None:

                    try:

                        print(
                            f"   Distance: "
                            f"{float(distance):.4f}"
                        )

                    except (
                        TypeError,
                        ValueError,
                    ):

                        pass

        # ----------------------------------------------------
        # Display Best Visual Evidence
        # ----------------------------------------------------

        print(
            "\n"
            + "=" * 60
        )

        print(
            "BEST VISUAL EVIDENCE"
        )

        print(
            "=" * 60
        )

        if not response.retrieved_images:

            print(
                "No relevant image/chart/graph found."
            )

        else:

            visual = response.retrieved_images[0]
            image_path = str(
                visual.get("image_path") or ""
            )

            try:
                image_link = Path(
                    image_path
                ).resolve().as_uri()
            except (OSError, ValueError):
                image_link = image_path

            print(
                f"Type: {visual.get('layout', 'image')}"
            )

            if visual.get("title"):
                print(
                    f"Title: {visual['title']}"
                )

            if visual.get("source_file"):
                print(
                    f"Source: {visual['source_file']}"
                )

            if visual.get("page_number") is not None:
                print(
                    f"Page: {visual['page_number']}"
                )

            print(
                f"Selection: "
                f"{visual.get('selection_method', 'visual_metadata')}"
            )

            print(
                f"Image path: {image_path}"
            )

            print(
                f"Image link: {image_link}"
            )

        # ----------------------------------------------------
        # Display Pipeline Information
        # ----------------------------------------------------

        print(
            "\n"
            + "=" * 60
        )

        print(
            "PIPELINE INFO"
        )

        print(
            "=" * 60
        )

        print(
            f"Language: "
            f"{response.detected_language}"
        )

        print(
            f"Query Type: "
            f"{response.query_type}"
        )

        print(
            f"Retrieved Chunks: "
            f"{response.retrieved_chunks}"
        )

        print(
            f"Context Chunks: "
            f"{response.context_chunks}"
        )

        print(
            f"Context Truncated: "
            f"{response.context_truncated}"
        )

        print(
            f"Processing Time: "
            f"{response.processing_time}s"
        )


# ============================================================
# Entry Point
# ============================================================

if __name__ == "__main__":
    main()
