"""
rag_pipeline.py

Main Retrieval-Augmented Generation (RAG) pipeline for JanMitra.

Pipeline:

User Question
    ->
QueryProcessor
    ->
Retriever
    ->
ContextBuilder
    ->
PromptBuilder
    ->
LLMClient
    ->
Groq API
    ->
Final Answer + Sources

This module orchestrates the complete query-time RAG workflow.

It does NOT handle:
- PDF extraction
- Text cleaning
- Chunk creation
- Document embedding
- ChromaDB ingestion

Those operations belong to the ingestion pipeline.
"""

from __future__ import annotations

import logging
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional


# ============================================================
# Project Imports
# ============================================================

from retrieval.query_processor import QueryProcessor
from retrieval.context_builder import ContextBuilder, BuiltContext
from retrieval.retriever import MultilingualRetriever

from rag.prompt_builder import PromptBuilder

from llm.llm_client import (
    LLMClient,
    LLMClientError,
)


# ============================================================
# Logging
# ============================================================

logger = logging.getLogger(__name__)


# ============================================================
# Custom Exceptions
# ============================================================

class RAGPipelineError(Exception):
    """
    Base exception for all RAG pipeline errors.
    """


class QueryProcessingError(RAGPipelineError):
    """
    Raised when query processing fails.
    """


class RetrievalError(RAGPipelineError):
    """
    Raised when document retrieval fails.
    """


class ContextBuildingError(RAGPipelineError):
    """
    Raised when context construction fails.
    """


class PromptBuildingError(RAGPipelineError):
    """
    Raised when prompt construction fails.
    """


class AnswerGenerationError(RAGPipelineError):
    """
    Raised when LLM answer generation fails.
    """


# ============================================================
# RAG Response Model
# ============================================================

@dataclass
class RAGResponse:
    """
    Final response returned by JanMitra's RAG pipeline.

    Attributes:
        question:
            Original citizen question.

        answer:
            Final LLM-generated answer.

        sources:
            Government document sources used in context.

        processed_query:
            Normalized query generated by QueryProcessor.

        retrieval_query:
            Query actually used for vector search.

        detected_language:
            Detected query language.

        query_type:
            Detected query intent.

        retrieved_chunks:
            Number of chunks returned by Retriever.

        context_chunks:
            Number of chunks actually sent to the LLM.

        context_truncated:
            Whether ContextBuilder truncated retrieved context.

        processing_time:
            Total execution time in seconds.

        metadata:
            Additional diagnostic information.
    """

    question: str

    answer: str

    sources: List[Dict[str, Any]]

    processed_query: str

    retrieval_query: str

    detected_language: str

    query_type: str

    retrieved_chunks: int

    context_chunks: int

    context_truncated: bool

    processing_time: float

    metadata: Dict[str, Any] = field(
        default_factory=dict
    )

    # Visual evidence corresponding to retrieved chunks. Defaults keep the
    # response source-compatible with callers constructing RAGResponse today.
    retrieved_images: List[Dict[str, Any]] = field(default_factory=list)

    def to_dict(
        self,
    ) -> Dict[str, Any]:
        """
        Convert response into a dictionary.

        Useful for FastAPI JSON responses.
        """

        return asdict(self)


# ============================================================
# RAG Pipeline
# ============================================================

class RAGPipeline:
    """
    Main JanMitra RAG pipeline.

    Example:

        pipeline = RAGPipeline()

        response = pipeline.query(
            "What are the eligibility conditions?"
        )

        print(response.answer)

        for source in response.sources:
            print(source)
    """

    def __init__(
        self,
        query_processor: Optional[
            QueryProcessor
        ] = None,
        retriever: Optional[
            MultilingualRetriever
        ] = None,
        context_builder: Optional[
            ContextBuilder
        ] = None,
        prompt_builder: Optional[
            PromptBuilder
        ] = None,
        llm_client: Optional[
            LLMClient
        ] = None,
        top_k: int = 5,
    ) -> None:
        """
        Initialize all RAG components.

        Dependencies can optionally be injected for testing.

        Args:
            query_processor:
                QueryProcessor instance.

            retriever:
                Retriever instance.

            context_builder:
                ContextBuilder instance.

            prompt_builder:
                PromptBuilder instance.

            llm_client:
                Groq LLMClient instance.

            top_k:
                Default number of document chunks to retrieve.
        """

        if top_k <= 0:

            raise ValueError(
                "top_k must be greater than 0."
            )

        self.top_k = top_k

        logger.info(
            "Initializing JanMitra RAG pipeline..."
        )

        # ----------------------------------------------------
        # Query Processor
        # ----------------------------------------------------

        try:

            self.query_processor = (
                query_processor
                or QueryProcessor()
            )

            logger.info(
                "QueryProcessor initialized."
            )

        except Exception as exc:

            logger.exception(
                "Failed to initialize QueryProcessor."
            )

            raise RAGPipelineError(
                f"Failed to initialize "
                f"QueryProcessor: {exc}"
            ) from exc

        # ----------------------------------------------------
        # Retriever
        # ----------------------------------------------------

        try:

            self.retriever = (
                retriever
                or MultilingualRetriever()
            )

            logger.info(
                "Retriever initialized."
            )

        except Exception as exc:

            logger.exception(
                "Failed to initialize Retriever."
            )

            raise RAGPipelineError(
                f"Failed to initialize "
                f"Retriever: {exc}"
            ) from exc

        # ----------------------------------------------------
        # Context Builder
        # ----------------------------------------------------

        try:

            self.context_builder = (
                context_builder
                or ContextBuilder(
                    max_chunks=top_k
                )
            )

            logger.info(
                "ContextBuilder initialized."
            )

        except Exception as exc:

            logger.exception(
                "Failed to initialize ContextBuilder."
            )

            raise RAGPipelineError(
                f"Failed to initialize "
                f"ContextBuilder: {exc}"
            ) from exc

        # ----------------------------------------------------
        # Prompt Builder
        # ----------------------------------------------------

        try:

            self.prompt_builder = (
                prompt_builder
                or PromptBuilder()
            )

            logger.info(
                "PromptBuilder initialized."
            )

        except Exception as exc:

            logger.exception(
                "Failed to initialize PromptBuilder."
            )

            raise RAGPipelineError(
                f"Failed to initialize "
                f"PromptBuilder: {exc}"
            ) from exc

        # ----------------------------------------------------
        # LLM Client
        # ----------------------------------------------------

        try:

            self.llm_client = (
                llm_client
                or LLMClient()
            )

            logger.info(
                "LLMClient initialized."
            )

        except Exception as exc:

            logger.exception(
                "Failed to initialize LLMClient."
            )

            raise RAGPipelineError(
                f"Failed to initialize "
                f"LLMClient: {exc}"
            ) from exc

        logger.info(
            "JanMitra RAG pipeline "
            "initialized successfully."
        )

    # ========================================================
    # Main Query Method
    # ========================================================

    def query(
        self,
        question: str,
        top_k: Optional[int] = None,
    ) -> RAGResponse:
        """
        Run the complete JanMitra RAG pipeline.

        Flow:

        1. Validate question
        2. Process query
        3. Retrieve relevant chunks
        4. Build context
        5. Build LLM prompts
        6. Generate answer with Groq
        7. Prepare source citations
        8. Return structured response

        Args:
            question:
                Citizen question.

            top_k:
                Optional number of retrieval results.

        Returns:
            RAGResponse
        """

        start_time = (
            time.perf_counter()
        )

        # ----------------------------------------------------
        # Validate Question
        # ----------------------------------------------------

        if not isinstance(
            question,
            str,
        ):

            raise TypeError(
                "question must be a string."
            )

        question = (
            question.strip()
        )

        if not question:

            raise ValueError(
                "question cannot be empty."
            )

        retrieval_top_k = (
            top_k
            if top_k is not None
            else self.top_k
        )

        if retrieval_top_k <= 0:

            raise ValueError(
                "top_k must be greater than 0."
            )

        logger.info(
            "Starting RAG query."
        )

        # ====================================================
        # STEP 1: Process Query
        # ====================================================

        try:

            processed = (
                self.query_processor.process(
                    question
                )
            )

        except Exception as exc:

            logger.exception(
                "Query processing failed."
            )

            raise QueryProcessingError(
                f"Failed to process query: {exc}"
            ) from exc

        # ----------------------------------------------------
        # Extract Processed Query Attributes Safely
        # ----------------------------------------------------

        normalized_query = getattr(
            processed,
            "normalized_query",
            question,
        )

        retrieval_query = getattr(
            processed,
            "retrieval_query",
            normalized_query,
        )

        detected_language = getattr(
            processed,
            "detected_language",
            "english",
        )

        query_type = getattr(
            processed,
            "query_type",
            "general",
        )

        keywords = getattr(
            processed,
            "keywords",
            [],
        )

        expanded_terms = getattr(
            processed,
            "expanded_terms",
            [],
        )

        logger.info(
            "Query processed | "
            "language=%s | "
            "type=%s",
            detected_language,
            query_type,
        )

        # ====================================================
        # STEP 2: Retrieve Relevant Document Chunks
        # ====================================================

        try:

            retrieved_results = (
                self._retrieve(
                    query=retrieval_query,
                    top_k=retrieval_top_k,
                )
            )

        except Exception as exc:

            logger.exception(
                "Document retrieval failed."
            )

            raise RetrievalError(
                f"Failed to retrieve "
                f"documents: {exc}"
            ) from exc

        # Ensure results are always list-like.

        if retrieved_results is None:

            retrieved_results = []

        try:

            retrieved_count = len(
                retrieved_results
            )

        except TypeError:

            retrieved_results = list(
                retrieved_results
            )

            retrieved_count = len(
                retrieved_results
            )

        logger.info(
            "Retrieval complete | "
            "chunks=%d",
            retrieved_count,
        )

        # ====================================================
        # STEP 3: Handle No Retrieval Results
        # ====================================================

        if not retrieved_results:

            processing_time = (
                time.perf_counter()
                - start_time
            )

            return RAGResponse(

                question=question,

                answer=(
                    self._no_information_answer(
                        detected_language
                    )
                ),

                sources=[],

                retrieved_images=[],

                processed_query=(
                    normalized_query
                ),

                retrieval_query=(
                    retrieval_query
                ),

                detected_language=(
                    detected_language
                ),

                query_type=(
                    query_type
                ),

                retrieved_chunks=0,

                context_chunks=0,

                context_truncated=False,

                processing_time=round(
                    processing_time,
                    4,
                ),

                metadata={
                    "status":
                        "no_retrieval_results",

                    "keywords":
                        keywords,

                    "expanded_terms":
                        expanded_terms,

                    "top_k":
                        retrieval_top_k,
                },
            )

        # ====================================================
        # STEP 4: Build LLM Context
        # ====================================================

        try:

            built_context = (
                self.context_builder.build(
                    retrieved_results
                )
            )

        except Exception as exc:

            logger.exception(
                "Context building failed."
            )

            raise ContextBuildingError(
                f"Failed to build "
                f"context: {exc}"
            ) from exc

        logger.info(
            "Context built | "
            "chunks=%d | "
            "characters=%d",
            built_context.total_chunks,
            built_context.total_characters,
        )

        # ====================================================
        # STEP 5: Handle Empty Context
        # ====================================================

        if (
            not built_context.context
            or not built_context.context.strip()
        ):

            processing_time = (
                time.perf_counter()
                - start_time
            )

            return RAGResponse(

                question=question,

                answer=(
                    self._no_information_answer(
                        detected_language
                    )
                ),

                sources=[],

                retrieved_images=[],

                processed_query=(
                    normalized_query
                ),

                retrieval_query=(
                    retrieval_query
                ),

                detected_language=(
                    detected_language
                ),

                query_type=(
                    query_type
                ),

                retrieved_chunks=(
                    retrieved_count
                ),

                context_chunks=0,

                context_truncated=(
                    built_context.truncated
                ),

                processing_time=round(
                    processing_time,
                    4,
                ),

                metadata={
                    "status":
                        "empty_context",

                    "keywords":
                        keywords,

                    "expanded_terms":
                        expanded_terms,

                    "top_k":
                        retrieval_top_k,
                },
            )

        # ====================================================
        # STEP 6: Build Prompt
        # ====================================================

        try:

            built_prompt = (
                self.prompt_builder.build(

                    question=question,

                    context=(
                        built_context.context
                    ),

                    language=(
                        detected_language
                    ),

                    query_type=(
                        query_type
                    ),
                )
            )

        except Exception as exc:

            logger.exception(
                "Prompt building failed."
            )

            raise PromptBuildingError(
                f"Failed to build "
                f"LLM prompt: {exc}"
            ) from exc

        logger.info(
            "LLM prompt built successfully."
        )

        # ====================================================
        # STEP 7: Generate Answer Using Groq
        # ====================================================

        try:

            answer = (
                self.llm_client.generate(
                    prompt=(
                        built_prompt.user_prompt
                    ),
                    system_prompt=(
                        built_prompt.system_prompt
                    ),
                    temperature=0.1,
                    max_tokens=1000,
                )
            )

        except LLMClientError as exc:

            logger.exception(
                "LLM answer generation failed."
            )

            raise AnswerGenerationError(
                f"Failed to generate "
                f"answer: {exc}"
            ) from exc

        except Exception as exc:

            logger.exception(
                "Unexpected LLM generation error."
            )

            raise AnswerGenerationError(
                f"Unexpected answer "
                f"generation error: {exc}"
            ) from exc

        # ====================================================
        # STEP 8: Prepare Sources
        # ====================================================

        sources = (
            self._prepare_sources(
                built_context
            )
        )

        image_results = retrieved_results

        if hasattr(self.retriever, "retrieve_best_image"):
            try:
                best_image_result = self.retriever.retrieve_best_image(
                    retrieval_query
                )
                image_results = (
                    [best_image_result]
                    if best_image_result is not None
                    else []
                )
            except Exception:
                # Visual evidence is optional and must never make an otherwise
                # grounded text answer fail.
                logger.exception(
                    "Dedicated image retrieval failed; "
                    "falling back to normal retrieval results."
                )

        retrieved_images = self._prepare_retrieved_images(image_results)

        # ====================================================
        # STEP 9: Build Final Response
        # ====================================================

        processing_time = (
            time.perf_counter()
            - start_time
        )

        response = RAGResponse(

            question=question,

            answer=answer,

            sources=sources,

            retrieved_images=retrieved_images,

            processed_query=(
                normalized_query
            ),

            retrieval_query=(
                retrieval_query
            ),

            detected_language=(
                detected_language
            ),

            query_type=(
                query_type
            ),

            retrieved_chunks=(
                retrieved_count
            ),

            context_chunks=(
                built_context.total_chunks
            ),

            context_truncated=(
                built_context.truncated
            ),

            processing_time=round(
                processing_time,
                4,
            ),

            metadata={
                "status":
                    "success",

                "keywords":
                    keywords,

                "expanded_terms":
                    expanded_terms,

                "context_characters":
                    built_context
                    .total_characters,

                "top_k":
                    retrieval_top_k,

                "llm_provider":
                    "groq",

                "llm_model":
                    getattr(
                        self.llm_client,
                        "model",
                        None,
                    ),
            },
        )

        logger.info(
            "RAG query completed | "
            "retrieved=%d | "
            "context=%d | "
            "time=%.4fs",
            retrieved_count,
            built_context.total_chunks,
            processing_time,
        )

        return response

    # ========================================================
    # Retrieval Adapter
    # ========================================================

    def _retrieve(
        self,
        query: str,
        top_k: int,
    ) -> List[Any]:
        """
        Execute semantic retrieval.

        Preferred Retriever interface:

            retriever.retrieve(
                query=query,
                top_k=top_k
            )

        Also supports:

            retriever.search(...)
        """

        # ----------------------------------------------------
        # Preferred retrieve() method
        # ----------------------------------------------------

        if hasattr(
            self.retriever,
            "retrieve",
        ):

            try:

                results = (
                    self.retriever.retrieve(
                        query=query,
                        top_k=top_k,
                    )
                )

            except TypeError:

                results = (
                    self.retriever.retrieve(
                        query,
                        top_k,
                    )
                )

            return (
                results
                if results is not None
                else []
            )

        # ----------------------------------------------------
        # Alternative search() method
        # ----------------------------------------------------

        if hasattr(
            self.retriever,
            "search",
        ):

            try:

                results = (
                    self.retriever.search(
                        query=query,
                        top_k=top_k,
                    )
                )

            except TypeError:

                results = (
                    self.retriever.search(
                        query,
                        top_k,
                    )
                )

            return (
                results
                if results is not None
                else []
            )

        raise AttributeError(
            "Retriever must implement "
            "either retrieve() or search()."
        )

    # ========================================================
    # Prepare Sources
    # ========================================================

    @staticmethod
    def _prepare_retrieved_images(results: List[Any]) -> List[Dict[str, Any]]:
        """Return only the highest-ranked visual match for API clients."""

        best_image: Optional[Dict[str, Any]] = None
        best_score = float("-inf")
        seen_paths = set()

        for result in results:
            if not isinstance(result, dict):
                continue

            metadata = result.get("metadata") or {}
            image_path = result.get("image_path") or metadata.get("image_path")

            if not image_path or image_path in seen_paths:
                continue

            image_path = str(image_path)
            stored_path = Path(image_path)

            if not stored_path.exists():
                normalized_parts = [
                    part.lower()
                    for part in stored_path.parts
                ]

                try:
                    images_index = normalized_parts.index("images")
                    relative_image_path = Path(
                        *stored_path.parts[images_index + 1:]
                    )
                    local_image_path = (
                        Path(__file__).resolve().parents[1]
                        / "data"
                        / "images"
                        / relative_image_path
                    )

                    if local_image_path.exists():
                        image_path = str(local_image_path)
                except (ValueError, OSError):
                    pass

            seen_paths.add(image_path)

            raw_score = result.get("similarity", result.get("score"))

            try:
                score = float(raw_score)
            except (TypeError, ValueError):
                # Retrieval results are already ordered best-first. An
                # unscored first visual remains the fallback unless a scored
                # visual match is available.
                score = float("-inf")

            image = {
                "image_path": image_path,
                "layout": result.get("layout") or metadata.get("layout", "image"),
                "coordinates": result.get("coordinates") or metadata.get("coordinates") or {},
                "source_file": metadata.get("source_file"),
                "page_number": metadata.get("page_number"),
                "chunk_id": result.get("chunk_id") or metadata.get("chunk_id"),
                "score": raw_score,
            }

            if best_image is None or score > best_score:
                best_image = image
                best_score = score

        return [best_image] if best_image is not None else []

    @staticmethod
    def _prepare_sources(
        built_context: BuiltContext,
    ) -> List[Dict[str, Any]]:
        """
        Convert ContextBuilder sources into API-friendly
        dictionaries.

        Duplicate source references are removed.

        NOTE on image_path/layout: ContextSource (defined in
        retrieval/context_builder.py) does NOT carry these as
        top-level attributes -- it carries the entire original
        chunk metadata dict verbatim in `source.metadata` (see
        ContextBuilder._build_sources(): `metadata=chunk.metadata`).
        So image_path/layout, if they were stored in ChromaDB's
        metadata for this chunk, live at `source.metadata["image_path"]`,
        not `source.image_path`. Reading them as attributes (an
        earlier version of this method did that) will silently
        always return None even when the data is right there.
        """

        sources: List[
            Dict[str, Any]
        ] = []

        seen = set()

        for source in (
            built_context.sources
        ):

            source_key = (

                source.file_name,

                source.page_number,

                source.chunk_id,
            )

            if source_key in seen:

                continue

            seen.add(
                source_key
            )

            source_metadata = (
                source.metadata or {}
            )

            layout = source_metadata.get(
                "layout"
            )

            image_path = source_metadata.get(
                "image_path"
            )

            source_dict: Dict[str, Any] = {
                "source_id":
                    source.source_id,

                "file_name":
                    source.file_name,

                "page_number":
                    source.page_number,

                "chunk_id":
                    source.chunk_id,

                "document_id":
                    source.document_id,

                "score":
                    source.score,

                "distance":
                    source.distance,
            }

            if layout is not None:

                source_dict["layout"] = layout

            if image_path:

                source_dict["image_path"] = image_path

            sources.append(
                source_dict
            )

        return sources

    # ========================================================
    # No Information Answer
    # ========================================================

    @staticmethod
    def _no_information_answer(
        language: str,
    ) -> str:
        """
        Return a localized fallback when retrieval fails.
        """

        normalized_language = (
            language
            or "english"
        ).lower()

        if normalized_language == "hindi":

            return (
                "उपलब्ध सरकारी दस्तावेज़ों में "
                "इस प्रश्न का उत्तर देने के लिए "
                "पर्याप्त जानकारी नहीं मिली।"
            )

        if normalized_language in {
            "hinglish",
            "mixed",
        }:

            return (
                "Available government documents mein "
                "is question ka answer dene ke liye "
                "sufficient information nahi mili."
            )

        return (
            "I could not find sufficient information "
            "in the available government documents "
            "to answer this question."
        )


# ============================================================
# Manual Test
# ============================================================

def main() -> None:
    """
    Interactive test for the complete JanMitra RAG pipeline.

    Before running:

    1. Government PDFs must already be processed.
    2. Chunks must already be embedded.
    3. Embeddings must already be stored in ChromaDB.
    4. backend/.env must contain GROQ_API_KEY.

    Run from backend directory:

        python -m rag.rag_pipeline
    """

    logging.basicConfig(
        level=logging.INFO,
        format=(
            "%(asctime)s | "
            "%(levelname)s | "
            "%(message)s"
        ),
    )

    print(
        "\n"
        + "=" * 60
    )

    print(
        "JANMITRA - COMPLETE RAG PIPELINE"
    )

    print(
        "=" * 60
    )

    # --------------------------------------------------------
    # Initialize Pipeline
    # --------------------------------------------------------

    try:

        pipeline = (
            RAGPipeline(
                top_k=5
            )
        )

    except Exception as exc:

        print(
            "\nFailed to initialize "
            "RAG pipeline:"
        )

        print(
            exc
        )

        return

    # --------------------------------------------------------
    # Display Configuration
    # --------------------------------------------------------

    print(
        "\nPipeline initialized successfully."
    )

    print(
        f"LLM Provider: Groq"
    )

    print(
    f"LLM Model: "
    f"{getattr(pipeline.llm_client, 'model', 'Unknown')}"
)

    print(
        f"Retrieval Top-K: "
        f"{pipeline.top_k}"
    )

    print(
        "\nAsk a question about the "
        "indexed government documents."
    )

    print(
        "Type 'exit' to stop."
    )

    # --------------------------------------------------------
    # Interactive Query Loop
    # --------------------------------------------------------

    while True:

        try:

            question = input(
                "\nYour question: "
            ).strip()

        except (
            KeyboardInterrupt,
            EOFError,
        ):

            print(
                "\nExiting JanMitra..."
            )

            break

        if question.lower() in {
            "exit",
            "quit",
            "q",
        }:

            print(
                "\nExiting JanMitra..."
            )

            break

        if not question:

            continue

        print(
            "\nSearching government "
            "documents..."
        )

        # ----------------------------------------------------
        # Execute Pipeline
        # ----------------------------------------------------

        try:

            response = (
                pipeline.query(
                    question
                )
            )

        except RAGPipelineError as exc:

            print(
                "\nRAG Pipeline Error:"
            )

            print(
                exc
            )

            continue

        except Exception as exc:

            logger.exception(
                "Unexpected pipeline error."
            )

            print(
                "\nUnexpected Error:"
            )

            print(
                exc
            )

            continue

        # ----------------------------------------------------
        # Display Answer
        # ----------------------------------------------------

        print(
            "\n"
            + "=" * 60
        )

        print(
            "ANSWER"
        )

        print(
            "=" * 60
        )

        print(
            response.answer
        )

        # ----------------------------------------------------
        # Display Sources
        # ----------------------------------------------------

        print(
            "\n"
            + "=" * 60
        )

        print(
            "SOURCES"
        )

        print(
            "=" * 60
        )

        if not response.sources:

            print(
                "No sources available."
            )

        else:

            for index, source in enumerate(
                response.sources,
                start=1,
            ):

                print(
    f"\n{index}. "
    f"{source.get('file_name', 'Unknown document')}"
)

                page_number = (
                    source.get(
                        "page_number"
                    )
                )

                if page_number is not None:

                    print(
                        f"   Page: "
                        f"{page_number}"
                    )

                score = (
                    source.get(
                        "score"
                    )
                )

                if score is not None:

                    try:

                        print(
                            f"   Score: "
                            f"{float(score):.4f}"
                        )

                    except (
                        TypeError,
                        ValueError,
                    ):

                        pass

                distance = (
                    source.get(
                        "distance"
                    )
                )

                if distance is not None:

                    try:

                        print(
                            f"   Distance: "
                            f"{float(distance):.4f}"
                        )

                    except (
                        TypeError,
                        ValueError,
                    ):

                        pass

                # NOTE: this is new -- previously image_path was
                # dropped in _prepare_sources() and never had
                # anywhere to be printed, even on the rare chance it
                # survived retrieval.
                image_path = source.get(
                    "image_path"
                )

                if image_path:

                    print(
                        f"   Image: "
                        f"{image_path}"
                    )

        # ----------------------------------------------------
        # Display Retrieved Images
        # ----------------------------------------------------

        print(
            "\n"
            + "=" * 60
        )

        print(
            "RETRIEVED IMAGES"
        )

        print(
            "=" * 60
        )

        if not response.retrieved_images:

            print(
                "No visual evidence retrieved."
            )

        else:

            for index, image in enumerate(
                response.retrieved_images,
                start=1,
            ):

                image_path = str(
                    image.get("image_path", "")
                )

                # A file URI is an actual link in terminals/IDEs that
                # support clickable links, while the normal path remains
                # visible and copyable in every terminal.
                try:

                    image_link = Path(
                        image_path
                    ).resolve().as_uri()

                except (OSError, ValueError):

                    image_link = image_path

                print(
                    f"\n{index}. "
                    f"{image.get('layout', 'image').title()}"
                )

                source_file = image.get("source_file")

                if source_file:

                    print(
                        f"   Source: {source_file}"
                    )

                page_number = image.get("page_number")

                if page_number is not None:

                    print(
                        f"   Page: {page_number}"
                    )

                print(
                    f"   Image path: {image_path}"
                )

                print(
                    f"   Image link: {image_link}"
                )

        # ----------------------------------------------------
        # Display Pipeline Information
        # ----------------------------------------------------

        print(
            "\n"
            + "=" * 60
        )

        print(
            "PIPELINE INFO"
        )

        print(
            "=" * 60
        )

        print(
            f"Language: "
            f"{response.detected_language}"
        )

        print(
            f"Query Type: "
            f"{response.query_type}"
        )

        print(
            f"Retrieved Chunks: "
            f"{response.retrieved_chunks}"
        )

        print(
            f"Context Chunks: "
            f"{response.context_chunks}"
        )

        print(
            f"Context Truncated: "
            f"{response.context_truncated}"
        )

        print(
            f"Processing Time: "
            f"{response.processing_time}s"
        )


# ============================================================
# Entry Point
# ============================================================

if __name__ == "__main__":
    main()
