import { createContext, useState, useEffect, useContext } from 'react'

export const LanguageContext = createContext()

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

const TRANSLATIONS = {
  hi: {
    // ===== NAVBAR =====
    search_placeholder: 'योजनाएं, सेवाएं या प्रश्न खोजें...',
    ask_ai: 'AI से पूछें',

    // ===== SIDEBAR =====
    explore: 'JanMitra AI खोजें',
    what_help: 'आज हम आपकी क्या मदद कर सकते हैं?',
    choose_service: 'कोई सेवा चुनें या AI सहायक से सीधे पूछें।',
    start_here: 'यहां से शुरू करें',
    home: 'होम',
    home_desc: 'आपका JanMitra AI प्रारंभिक बिंदु',
    ask_janmitra: 'JanMitra AI से पूछें',
    ask_desc: 'त्वरित कल्याण मार्गदर्शन प्राप्त करें',
    citizen_tools: 'नागरिक उपकरण',
    scheme_finder: 'योजना खोजें',
    scheme_desc: 'लाभ खोजें',
    checklist: 'चेकलिस्ट',
    checklist_desc: 'दस्तावेज तैयार करें',
    grievance: 'शिकायत',
    grievance_desc: 'समस्या का समाधान करें',
    feedback: 'प्रतिक्रिया',
    responsible_ai: 'उत्तरदायी AI',
    admin: 'प्रशासन',
    independent_tool: 'स्वतंत्र सहायता उपकरण',
    not_official: 'सरकारी सेवा नहीं।',

    // ===== HOME PAGE =====
    hero_badge: 'AI-संचालित · उत्तर प्रदेश',
    hero_title: 'सरकारी योजनाएं\nजटिल नहीं होनी चाहिए।',
    hero_sub: 'JanMitra AI नागरिकों को कल्याण योजनाओं, दस्तावेजों, पात्रता और सरकारी सेवाओं को बिना जटिल कागजी कार्रवाई के समझने में मदद करता है।',
    start_here_btn: 'यहां से शुरू करें',
    ask_janmitra_btn: 'JanMitra AI से पूछें',
    discover_schemes: 'मेरी योजनाएं खोजें',
    what_need: 'आपको क्या चाहिए?',
    choose_task: 'कोई कार्य चुनें।\nहम मार्गदर्शन करेंगे।',
    find_schemes: 'योजनाएं खोजें',
    find_schemes_desc: 'अपनी आयु, व्यवसाय और श्रेणी के आधार पर सरकारी योजनाएं खोजें।',
    documents: 'दस्तावेज',
    documents_desc: 'कार्यालय जाने से पहले जानें कि आपको किन दस्तावेजों की आवश्यकता है।',
    raise_grievance: 'शिकायत दर्ज करें',
    raise_grievance_desc: 'शिकायत प्रक्रियाओं को समझें और औपचारिक शिकायत तैयार करें।',
    built_to: 'सार्वजनिक सेवाओं को समझने में आसान बनाने के लिए बनाया गया।',
    built_desc: 'कल्याण सूचना, दस्तावेज मार्गदर्शन और नागरिक सहायता के लिए एक सरल इंटरफेस।',
    beneficiaries: 'लाभार्थी',
    welfare_schemes: 'कल्याण योजनाएं',
    ai_assistance: 'AI सहायता',
    uttar_pradesh: 'उत्तर प्रदेश',
    need_human_help: 'मानव सहायता चाहिए?',
    important_helplines: 'महत्वपूर्ण हेल्पलाइन',

    // ===== CHAT PAGE =====
    online: 'JANMITRA AI ऑनलाइन है',
    ask: 'पूछें।\nसमझें।\nकार्रवाई करें।',
    chat_sub: 'उत्तर प्रदेश में कल्याण योजनाओं, राशन कार्ड, दस्तावेजों और सरकारी सेवाओं के लिए सरल मार्गदर्शन।',
    current_session: 'वर्तमान सत्र',
    new_chat: 'नई चैट',
    your_questions: 'आपके प्रश्न यहां दिखाई देंगे।',
    suggested_topics: 'सुझाए गए विषय',
    chat_welcome: 'नमस्ते! मैं JanMitra AI हूं, उत्तर प्रदेश के लिए आपका कल्याण सहायक। मुझे बताएं कि आप क्या करना चाहते हैं और मैं आपको अगले कदम समझने में मदद करूंगा।',
    ration_cards: 'राशन कार्ड',
    welfare_schemes_chat: 'कल्याण योजनाएं',
    documents_chat: 'दस्तावेज',
    grievances_chat: 'शिकायतें',
    what_help_today: 'आज मैं आपकी क्या मदद कर सकता हूं?',
    ask_anything: 'JanMitra AI से कुछ भी पूछें...',
    ai_guidance: 'AI मार्गदर्शन केवल सूचनात्मक है। आधिकारिक स्रोतों से महत्वपूर्ण जानकारी सत्यापित करें।',
    export: 'निर्यात',
    clear: 'साफ़ करें',

    // ===== SCHEMES PAGE =====
    personalized_welfare: 'व्यक्तिगत कल्याण खोज',
    schemes_title: 'सरकारी योजनाएं\nअपनी प्रोफ़ाइल के लिए बनाई गई।',
    schemes_sub: 'हमें कुछ बुनियादी विवरण बताएं और JanMitra AI आपकी प्रोफ़ाइल को प्रासंगिक कल्याण योजनाओं, लाभों और आवश्यक दस्तावेजों से मिलाएगा।',
    profile_details: 'प्रोफ़ाइल विवरण',
    tell_about_self: 'अपने बारे में बताएं',
    your_age: 'आपकी आयु',
    example_age: 'उदाहरण: 45',
    what_do: 'आप क्या करते हैं?',
    farmer: 'किसान',
    labour: 'दिहाड़ी मजदूर',
    student: 'छात्र',
    unemployed: 'बेरोजगार / गृहणी',
    other: 'अन्य / नौकरीपेशा',
    social_category: 'सामाजिक श्रेणी',
    annual_income: 'वार्षिक पारिवारिक आय',
    optional: 'वैकल्पिक',
    find_my_schemes: 'मेरी योजनाएं खोजें',
    privacy_first: 'गोपनीयता पहले',
    privacy_desc: 'आपकी प्रोफ़ाइल का उपयोग केवल योजना मिलान की गणना के लिए किया जाता है।',
    your_results: 'आपके परिणाम',
    recommended_schemes: 'अनुशंसित योजनाएं',
    matching_complete: 'मिलान पूरा हुआ',
    schemes_found: 'आपके लिए योजनाएं मिलीं',
    what_you_get: 'आपको क्या मिलता है',
    documents_needed: 'आवश्यक दस्तावेज',
    visit_official: 'आधिकारिक पोर्टल पर जाएं',
    important: 'महत्वपूर्ण',
    scheme_disclaimer: 'JanMitra AI केवल शैक्षिक उद्देश्यों के लिए AI-जनित मार्गदर्शन प्रदान करता है। आधिकारिक स्रोतों से महत्वपूर्ण जानकारी सत्यापित करें।',
    your_matches: 'आपके मैच यहां दिखाई देंगे',
    complete_profile: 'अपनी प्रोफ़ाइल पूरी करें और हम उपलब्ध कल्याण योजनाओं को उपयुक्त मैचों के लिए खोजेंगे।',
    eligibility: 'पात्रता',
    benefits: 'लाभ',

    // ===== CHECKLIST PAGE =====
    doc_prep_desk: 'दस्तावेज तैयारी डेस्क',
    checklist_title: 'अपने दस्तावेज\nजाने से पहले तैयार करें।',
    checklist_sub: 'वह सरकारी सेवा चुनें जिसके लिए आप आवेदन कर रहे हैं। JanMitra AI आपके लिए एक स्पष्ट दस्तावेज चेकलिस्ट तैयार करेगा।',
    gov_service: 'सरकारी सेवा',
    choose_service: 'अपनी सेवा चुनें',
    select_service: 'सेवा चुनें',
    collect_docs: 'दस्तावेज एकत्र करें',
    tick_ready: 'तैयार होने पर प्रत्येक को टिक करें।',
    take_checklist: 'अपनी चेकलिस्ट लें',
    print_save: 'इसे प्रिंट करें या PDF के रूप में सहेजें।',
    quick_tip: 'त्वरित सुझाव',
    tip_text: 'कार्यालय जाने से पहले मूल और फोटोकॉपी एक साथ रखें।',
    waiting_service: 'सेवा की प्रतीक्षा',
    checklist_here: 'आपकी चेकलिस्ट यहां दिखाई देगी।',
    select_left: 'शुरू करने के लिए बाएं पैनल से एक सरकारी सेवा चुनें।',
    doc_requirement: 'दस्तावेज आवश्यकता शीट',
    processing: 'प्रसंस्करण',
    application_fee: 'आवेदन शुल्क',
    doc_readiness: 'दस्तावेज तैयारी',
    collected: 'एकत्रित',
    required_docs: 'आवश्यक दस्तावेज',
    required: 'आवश्यक',
    optional_badge: 'वैकल्पिक',
    req_note: 'आपके मामले के आधार पर आवश्यकताएं भिन्न हो सकती हैं। जमा करने से पहले संबंधित विभाग से महत्वपूर्ण विवरण की पुष्टि करें।',

    // ===== GRIEVANCE PAGE =====
    citizen_resolution: 'नागरिक समाधान डेस्क',
    grievance_title: 'पता नहीं\nअपनी शिकायत कहां दर्ज करें?',
    grievance_sub: 'अपनी समस्या चुनें, आधिकारिक उन्नयन पथ का पालन करें, और प्रक्रिया में खोए बिना एक औपचारिक शिकायत तैयार करें।',
    guided_process: 'निर्देशित प्रक्रिया',
    three_stages: '3 सरल चरण',
    identify: 'पहचानें',
    resolve: 'समाधान करें',
    escalate: 'उन्नयन करें',
    start_here_grievance: 'यहां से शुरू करें',
    what_went_wrong: 'क्या गलत हुआ?',
    resolution_route: 'समाधान मार्ग',
    follow_path: 'अपना उन्नयन पथ का पालन करें',
    escalation_tool: 'उन्नयन उपकरण',
    complaint_title: 'अपनी समस्या को\nऔपचारिक शिकायत में बदलें।',
    complaint_sub: 'आवश्यक विवरण प्रदान करें और JanMitra AI संबंधित प्राधिकारी के लिए एक संरचित शिकायत मसौदा तैयार करेगा।',
    your_details: 'आपका विवरण',
    name_location: 'नाम और स्थान की जानकारी',
    describe_problem: 'समस्या का वर्णन करें',
    explain_happened: 'बताएं कि वास्तव में क्या हुआ',
    get_draft: 'मसौदा प्राप्त करें',
    ready_letter: 'तैयार शिकायत पत्र प्राप्त करें',
    complaint_builder: 'शिकायत निर्माता',
    citizen_info: 'नागरिक सूचना',
    form_data: 'फॉर्म डेटा',
    full_name: 'पूरा नाम',
    district: 'जिला',
    block_tehsil: 'ब्लॉक / तहसील',
    village_ward: 'गांव / वार्ड',
    issue_type: 'समस्या का प्रकार',
    select_category: '— आधिकारिक समस्या श्रेणी चुनें —',
    issue_desc: 'समस्या का विवरण',
    incident_date: 'घटना की तारीख',
    previous_complaint: 'पिछली शिकायत संख्या',
    generate_complaint: 'शिकायत मसौदा तैयार करें',
    document_ready: 'दस्तावेज तैयार है',
    your_complaint: 'आपकी शिकायत का मसौदा',
    generated: 'तैयार',
    formal_letter: 'औपचारिक पत्र',
    complaint_draft: 'शिकायत मसौदा',
    what_now: 'अब क्या?',
    submission_route: 'जमा करने का मार्ग',
    need_direct_help: 'सीधी मदद चाहिए?',
    official_contacts: 'आधिकारिक संपर्क',
    current_case: 'वर्तमान मामला',
    actions: 'कार्रवाई',
    action: 'कार्रवाई',

    // ===== FEEDBACK PAGE =====
    citizen_voice: 'नागरिक आवाज',
    feedback_title: 'हमें बताएं कि\nवास्तव में क्या काम किया।',
    feedback_sub: 'एक रेटिंग JanMitra AI को अगले नागरिक के लिए स्पष्ट, तेज और अधिक उपयोगी बनाने में मदद कर सकती है।',
    your_experience: 'आपका अनुभव',
    how_did_do: 'JanMitra AI ने कैसा किया?',
    your_rating: 'आपकी रेटिंग',
    select_rating: '1 — 5 चुनें',
    what_reviewing: 'आप क्या समीक्षा कर रहे हैं?',
    choose_feature: 'वह हिस्सा चुनें जिसका आपने उपयोग किया।',
    speak_freely: 'स्वतंत्र रूप से बोलें',
    what_change: 'हमें क्या\nबदलना चाहिए?',
    feedback_placeholder: 'अपना अनुभव यहां लिखें...',
    feedback_used: 'प्रतिक्रिया का उपयोग JanMitra AI को बेहतर बनाने के लिए किया जाता है',
    send_feedback: 'प्रतिक्रिया भेजें',
    feedback_received: 'प्रतिक्रिया प्राप्त हुई',
    thank_you: 'हमें सुधारने में मदद करने के लिए धन्यवाद।',
    what_happens_next: 'आगे क्या होता है',
    feedback_impact: 'आपकी प्रतिक्रिया\nयहां नहीं रुकती।',
    improve_accuracy: 'AI सटीकता में सुधार करें',
    improve_accuracy_desc: 'रेटिंग यह पहचानने में मदद करती है कि AI उत्तर कहां स्पष्ट और अधिक सटीक हो सकते हैं।',
    serve_more: 'अधिक नागरिकों की सेवा करें',
    serve_more_desc: 'बेहतर अनुभव उत्तर प्रदेश भर में कल्याण सूचना तक पहुंच को आसान बनाते हैं।',
    build_trust: 'उत्तरदायी AI बनाएं',
    build_trust_desc: 'नकारात्मक प्रतिक्रिया संभावित मुद्दों को सतह पर लाने में मदद करती है जिन पर ध्यान देने की आवश्यकता है।',
    accuracy: 'सटीकता',
    access: 'पहुंच',
    trust: 'विश्वास',
    feedback_disclaimer: 'JanMitra AI केवल शैक्षिक उद्देश्यों के लिए AI-जनित मार्गदर्शन प्रदान करता है। यह भारत सरकार की आधिकारिक सेवा नहीं है।',

    // ===== DISCLAIMER PAGE =====
    trust_charter: 'विश्वास घोषणापत्र',
    responsible_ai: 'उत्तरदायी कृत्रिम बुद्धिमत्ता',
    guidance_ai: 'AI के साथ मार्गदर्शन।\nआपके साथ निर्णय।',
    disclaimer_sub: 'JanMitra AI क्या करता है, इसकी सीमाएं कहां हैं, और AI-संचालित कल्याण मार्गदर्शन का उपयोग करने से पहले आपकी जानकारी कैसे संभाली जाती है, इसे समझें।',
    transparency_first: 'पारदर्शिता पहले',
    read_before_use: 'उपयोग से पहले पढ़ें',
    not_gov_service: 'JanMitra AI सरकारी सेवा नहीं है।',
    notice_001: 'सूचना / 001',
    not_gov_desc: 'JanMitra AI केवल शैक्षिक और सहायता उद्देश्यों के लिए AI-जनित मार्गदर्शन प्रदान करता है। यह भारत सरकार की आधिकारिक सेवा नहीं है और न ही कानूनी या प्रशासनिक अनुमोदन प्रदान करता है।',
    verify_info: 'उपयोगकर्ताओं को कार्रवाई करने से पहले संबंधित सरकारी विभाग के साथ महत्वपूर्ण जानकारी, पात्रता शर्तों, दस्तावेजों, समय-सीमा और प्रक्रियाओं को स्वतंत्र रूप से सत्यापित करना चाहिए।',
    operational_boundaries: 'परिचालन सीमाएं',
    know_limits: 'जानें कि AI कहां रुकता है।',
    assist_explain: 'सहायता और व्याख्या करें',
    janmitra_can: 'JANMITRA AI कर सकता है',
    janmitra_cannot: 'JANMITRA AI नहीं कर सकता',
    can_1: 'सरकारी योजना पात्रता और लाभों की व्याख्या करें।',
    can_2: 'कल्याण सेवाओं के लिए दस्तावेज आवश्यकताओं की सूची बनाएं।',
    can_3: 'शिकायत मार्गदर्शन और प्रक्रियात्मक चरण प्रदान करें।',
    can_4: 'मानकीकृत शिकायत पत्र टेम्पलेट तैयार करें।',
    can_5: 'प्रमुख जीवन घटनाओं के आधार पर प्रासंगिक योजनाओं की पहचान करें।',
    cannot_1: 'वास्तविक सरकारी आवेदनों को संसाधित या जमा न करें।',
    cannot_2: 'योजना पात्रता, धन या अनुमोदन की गारंटी न दें।',
    cannot_3: 'आधिकारिक सरकारी रिकॉर्ड तक पहुंच, संशोधन या सत्यापन न करें।',
    cannot_4: 'कानूनी रूप से बाध्यकारी सलाह या प्रतिनिधित्व प्रदान न करें।',
    cannot_5: 'आपकी ओर से प्रशासनिक निर्णय न लें।',
    data_protocol: 'डेटा प्रोटोकॉल',
    what_happens_data: 'आपके डेटा का क्या होता है?',
    data_desc: 'JanMitra AI के माध्यम से जानकारी कैसे चलती है, इसका एक सरल दृश्य।',
    you_interact: 'आप बातचीत करते हैं',
    you_interact_desc: 'जब आप इसकी सुविधाओं का उपयोग करते हैं तो चैट प्रश्न या दस्तावेज सिस्टम को प्रदान किए जाते हैं।',
    system_processes: 'सिस्टम प्रक्रिया करता है',
    system_processes_desc: 'मार्गदर्शन, OCR परिणाम या प्रासंगिक प्रतिक्रियाएं उत्पन्न करने के लिए जानकारी संसाधित की जाती है।',
    sensitive_leave: 'संवेदनशील फाइलें चली जाती हैं',
    sensitive_leave_desc: 'अपलोड किए गए दस्तावेजों को संसाधित किया जाता है और तुरंत हटा दिया जाता है। चैट वार्तालाप स्थायी रूप से संग्रहीत नहीं किए जाते हैं।',
    no_identity_vault: 'कोई पहचान तिजोरी नहीं',
    no_identity_vault_desc: 'कोई आधार, बैंक या पहचान डेटा संग्रहीत नहीं किया जाता है।',
    anonymous_telemetry: 'अनाम टेलीमेट्री',
    anonymous_telemetry_desc: 'केवल अनामीकृत रेटिंग और टिप्पणियां बनाए रखी जाती हैं।',
    local_knowledge: 'स्थानीय ज्ञान',
    local_knowledge_desc: 'योजना और FAQ जानकारी स्थानीय डेटा फ़ाइलों का उपयोग करती है।',
    browser_preferences: 'ब्राउज़र प्राथमिकताएं',
    browser_preferences_desc: 'localStorage भाषा और थीम प्राथमिकताओं को संग्रहीत करता है।',
    external_processing: 'बाहरी प्रसंस्करण:',
    external_processing_desc: 'JanMitra AI LLM अनुमान के लिए Groq API का उपयोग करता है, जो Groq की गोपनीयता नीति के अधीन है।',
    behind_janmitra: 'JanMitra AI के पीछे क्या है?',
    system_desc: 'JanMitra AI HCLTech हैकथॉन के लिए बनाया गया एक AI-संचालित कल्याण सहायता उपकरण है।',
    verify_official: 'आधिकारिक स्रोतों पर जारी रखें।',
    verify_desc: 'हमेशा उचित सरकारी पोर्टल के साथ सीधे महत्वपूर्ण जानकारी सत्यापित करें।',
    responsible_ai_principle: 'JANMITRA AI उत्तरदायी AI सिद्धांत',
    principle_text: 'AI को सरकारी जानकारी को समझने में आसान बनाना चाहिए — सरकार होने का दिखावा नहीं करना चाहिए।',

    // ===== ADMIN PAGE =====
    live_system: 'लाइव सिस्टम अवलोकन',
    see_inside: 'देखें क्या हो रहा है\nJanMitra AI के अंदर।',
    admin_desc: 'वास्तविक नागरिक बातचीत, AI उपयोग और प्रतिक्रिया — सीधे वर्तमान एप्लिकेशन लॉग से प्रस्तुत।',
    latest_metrics: 'नवीनतम मेट्रिक्स',
    refresh_dashboard: 'डैशबोर्ड ताज़ा करें',
    ai_queries: 'AI प्रश्न',
    total_conversations: 'कुल बातचीत संभाली गई',
    positive: 'सकारात्मक',
    helpful_responses: 'सहायक प्रतिक्रियाएं रिपोर्ट की गईं',
    needs_work: 'सुधार की आवश्यकता',
    negative_responses: 'नकारात्मक प्रतिक्रियाएं रिपोर्ट की गईं',
    satisfaction: 'संतुष्टि',
    overall_feedback: 'समग्र प्रतिक्रिया प्रदर्शन',
    discovery: 'खोज',
    what_ask_most: 'नागरिक सबसे ज्यादा क्या पूछते हैं।',
    activity: 'गतिविधि',
    feedback_feed: 'नागरिक प्रतिक्रिया फीड।',
    no_query: 'अभी तक कोई प्रश्न गतिविधि नहीं।',
    no_feedback: 'अभी तक कोई प्रतिक्रिया दर्ज नहीं की गई।',
    data_integrity: 'डेटा अखंडता',
    data_integrity_desc: 'यहां दिखाई गई प्रत्येक संख्या वास्तविक JanMitra AI गतिविधि से आती है। कोई डेमो सांख्यिकी या निर्मित सहभागिता संख्याएं सम्मिलित नहीं की गई हैं।',
  },

  hinglish: {
    // ===== NAVBAR =====
    search_placeholder: 'Schemes, services ya questions search karo...',
    ask_ai: 'AI se Poocho',

    // ===== SIDEBAR =====
    explore: 'JanMitra AI Explore karo',
    what_help: 'Aaj hum aapki kya help kar sakte hain?',
    choose_service: 'Koi service chuno ya AI assistant se seedha poocho.',
    start_here: 'Yahan se shuru karo',
    home: 'Home',
    home_desc: 'Aapka JanMitra AI starting point',
    ask_janmitra: 'JanMitra AI se Poocho',
    ask_desc: 'Instant welfare guidance lo',
    citizen_tools: 'Citizen tools',
    scheme_finder: 'Scheme Finder',
    scheme_desc: 'Benefits discover karo',
    checklist: 'Checklist',
    checklist_desc: 'Documents prepare karo',
    grievance: 'Grievance',
    grievance_desc: 'Issue resolve karo',
    feedback: 'Feedback',
    responsible_ai: 'Responsible AI',
    admin: 'Admin',
    independent_tool: 'Independent assistance tool',
    not_official: 'Official Government service nahi.',

    // ===== HOME PAGE =====
    hero_badge: 'AI-Powered · Uttar Pradesh',
    hero_title: 'Sarkari Yojnayen\nComplex nahi honi chahiye.',
    hero_sub: 'JanMitra AI citizens ko welfare schemes, documents, eligibility aur government services samajhne mein help karta hai — bina confusing paperwork ke.',
    start_here_btn: 'Yahan se shuru karo',
    ask_janmitra_btn: 'JanMitra AI se Poocho',
    discover_schemes: 'Meri Yojnayen Dhundho',
    what_need: 'Tumhe kya chahiye?',
    choose_task: 'Koi task chuno.\nHum guide karenge.',
    find_schemes: 'Yojnayen Dhundho',
    find_schemes_desc: 'Apni umar, pesha aur category ke hisaab se government schemes dhundho.',
    documents: 'Documents',
    documents_desc: 'Office jaane se pehle jaano ki kaunse documents chahiye.',
    raise_grievance: 'Shikayat Darj Karo',
    raise_grievance_desc: 'Shikayat processes samjho aur formal complaint tayar karo.',
    built_to: 'Public services ko samajhne mein aasan banane ke liye banaya gaya.',
    built_desc: 'Welfare information, document guidance aur citizen assistance ke liye ek simple interface.',
    beneficiaries: 'Beneficiaries',
    welfare_schemes: 'Welfare Schemes',
    ai_assistance: 'AI Assistance',
    uttar_pradesh: 'Uttar Pradesh',
    need_human_help: 'Human help chahiye?',
    important_helplines: 'Important Helplines',

    // ===== CHAT PAGE =====
    online: 'JANMITRA AI ONLINE HAI',
    ask: 'Poochho.\nSamjho.\nAction Lo.',
    chat_sub: 'UP mein welfare schemes, ration card, documents aur government services ke liye simple guidance.',
    current_session: 'Current Session',
    new_chat: 'Nayi Chat',
    your_questions: 'Tumhare questions yahan dikhenge.',
    suggested_topics: 'Suggested Topics',
    chat_welcome: 'Namaste! Main JanMitra AI hoon, UP ka aapka welfare assistant. Mujhe batao aap kya karna chahte ho aur main agle steps samjhaunga.',
    ration_cards: 'Ration Cards',
    welfare_schemes_chat: 'Welfare Schemes',
    documents_chat: 'Documents',
    grievances_chat: 'Grievances',
    what_help_today: 'Aaj main aapki kya help kar sakta hoon?',
    ask_anything: 'JanMitra AI se kuch bhi poocho...',
    ai_guidance: 'AI guidance sirf informative hai. Official sources se important info verify karo.',
    export: 'Export',
    clear: 'Clear',

    // ===== SCHEMES PAGE =====
    personalized_welfare: 'Personalized Welfare Discovery',
    schemes_title: 'Government Schemes\nTumhari profile ke liye.',
    schemes_sub: 'Kuch basic details batao aur JanMitra AI tumhari profile ko relevant welfare schemes, benefits aur documents se match karega.',
    profile_details: 'Profile Details',
    tell_about_self: 'Apne baare mein batao',
    your_age: 'Tumhari Umar',
    example_age: 'Example: 45',
    what_do: 'Tum kya karte ho?',
    farmer: 'Kisan',
    labour: 'Daily Wage Labour',
    student: 'Student',
    unemployed: 'Unemployed / Homemaker',
    other: 'Other / Salaried',
    social_category: 'Social Category',
    annual_income: 'Annual Family Income',
    optional: 'Optional',
    find_my_schemes: 'Meri Yojnayen Dhundho',
    privacy_first: 'Privacy first',
    privacy_desc: 'Tumhari profile sirf scheme matches calculate karne ke liye use hoti hai.',
    your_results: 'Tumhare Results',
    recommended_schemes: 'Recommended Schemes',
    matching_complete: 'Matching Complete',
    schemes_found: 'tumhare liye schemes mili',
    what_you_get: 'Tumhe kya milta hai',
    documents_needed: 'Documents Needed',
    visit_official: 'Official Portal par jao',
    important: 'Important',
    scheme_disclaimer: 'JanMitra AI sirf educational purposes ke liye AI-generated guidance provide karta hai. Official sources se important info verify karo.',
    your_matches: 'Tumhare matches yahan dikhenge',
    complete_profile: 'Apni profile complete karo aur hum available welfare schemes mein suitable matches dhundhenge.',
    eligibility: 'Eligibility',
    benefits: 'Benefits',

    // ===== CHECKLIST PAGE =====
    doc_prep_desk: 'Document Preparation Desk',
    checklist_title: 'Apne documents\njaane se pehle tayar karo.',
    checklist_sub: 'Woh government service choose karo jiske liye apply kar rahe ho. JanMitra AI tumhare liye document checklist tayar karega.',
    gov_service: 'Government Service',
    choose_service: 'Apni Service Chuno',
    select_service: 'Service Chuno',
    collect_docs: 'Documents Collect karo',
    tick_ready: 'Ready hone par har ek ko tick karo.',
    take_checklist: 'Apni Checklist Lo',
    print_save: 'Isko print karo ya PDF mein save karo.',
    quick_tip: 'Quick Tip',
    tip_text: 'Office jaane se pehle originals aur photocopies ek saath rakho.',
    waiting_service: 'Service ki Waiting',
    checklist_here: 'Tumhari checklist yahan dikhegi.',
    select_left: 'Shuru karne ke liye left panel se government service chuno.',
    doc_requirement: 'Document Requirement Sheet',
    processing: 'Processing',
    application_fee: 'Application Fee',
    doc_readiness: 'Document Readiness',
    collected: 'Collected',
    required_docs: 'Required Documents',
    required: 'Required',
    optional_badge: 'Optional',
    req_note: 'Tumhare case ke hisaab se requirements different ho sakti hain. Submit karne se pehle concerned department se important details confirm karo.',

    // ===== GRIEVANCE PAGE =====
    citizen_resolution: 'Citizen Resolution Desk',
    grievance_title: 'Pata nahi\napni shikayat kahan darj karein?',
    grievance_sub: 'Apni problem chuno, official escalation path follow karo, aur formal complaint tayar karo — process mein khoye bina.',
    guided_process: 'Guided Process',
    three_stages: '3 Simple Stages',
    identify: 'Identify',
    resolve: 'Resolve',
    escalate: 'Escalate',
    start_here_grievance: 'Yahan se shuru karo',
    what_went_wrong: 'Kya galat hua?',
    resolution_route: 'Resolution Route',
    follow_path: 'Apna escalation path follow karo',
    escalation_tool: 'Escalation Tool',
    complaint_title: 'Apni problem ko\nformal complaint mein badlo.',
    complaint_sub: 'Zaroori details do aur JanMitra AI concerned authority ke liye structured complaint draft tayar karega.',
    your_details: 'Tumhare Details',
    name_location: 'Name aur location information',
    describe_problem: 'Problem Describe karo',
    explain_happened: 'Batao exactly kya hua',
    get_draft: 'Draft Lo',
    ready_letter: 'Ready complaint letter lo',
    complaint_builder: 'Complaint Builder',
    citizen_info: 'Citizen Information',
    form_data: 'Form Data',
    full_name: 'Full Name',
    district: 'District',
    block_tehsil: 'Block / Tehsil',
    village_ward: 'Village / Ward',
    issue_type: 'Issue Type',
    select_category: '— Official Issue Category Chuno —',
    issue_desc: 'Issue Description',
    incident_date: 'Incident Date',
    previous_complaint: 'Previous Complaint No.',
    generate_complaint: 'Complaint Draft Generate Karo',
    document_ready: 'Document Ready Hai',
    your_complaint: 'Tumhara Complaint Draft',
    generated: 'Generated',
    formal_letter: 'Formal Letter',
    complaint_draft: 'Complaint Draft',
    what_now: 'Ab Kya?',
    submission_route: 'Submission Route',
    need_direct_help: 'Direct Help Chahiye?',
    official_contacts: 'Official Contacts',
    current_case: 'Current Case',
    actions: 'Actions',
    action: 'Action',

    // ===== FEEDBACK PAGE =====
    citizen_voice: 'Citizen Voice',
    feedback_title: 'Hamein batao\nasli mein kya kaam kiya.',
    feedback_sub: 'Ek rating JanMitra AI ko agle citizen ke liye clear, fast aur useful banane mein help kar sakti hai.',
    your_experience: 'Tumhara Experience',
    how_did_do: 'JanMitra AI ne kaisa kiya?',
    your_rating: 'Tumhari Rating',
    select_rating: '1 — 5 Chuno',
    what_reviewing: 'Tum kya review kar rahe ho?',
    choose_feature: 'Woh part chuno jo tumne use kiya.',
    speak_freely: 'Speak Freely',
    what_change: 'Hamein kya\nchange karna chahiye?',
    feedback_placeholder: 'Apna experience yahan likho...',
    feedback_used: 'Feedback JanMitra AI ko better banane ke liye use hota hai',
    send_feedback: 'Feedback Bhejo',
    feedback_received: 'Feedback Mil Gaya',
    thank_you: 'Hamein improve karne mein help karne ke liye shukriya.',
    what_happens_next: 'Agla Kya Hota Hai',
    feedback_impact: 'Tumhara feedback\nyahan nahi rukta.',
    improve_accuracy: 'AI Accuracy Improve Karo',
    improve_accuracy_desc: 'Ratings help karti hain identify karne mein ki AI answers kahan clear aur accurate ho sakte hain.',
    serve_more: 'Aur Citizens Ki Service Karo',
    serve_more_desc: 'Better experiences welfare information ko UP bhar mein accessible banate hain.',
    build_trust: 'Responsible AI Banao',
    build_trust_desc: 'Negative feedback potential issues ko surface karne mein help karti hai jin par attention chahiye.',
    accuracy: 'Accuracy',
    access: 'Access',
    trust: 'Trust',
    feedback_disclaimer: 'JanMitra AI sirf educational purposes ke liye AI-generated guidance provide karta hai. Yeh official Government of India service nahi hai.',

    // ===== DISCLAIMER PAGE =====
    trust_charter: 'Trust Charter',
    responsible_ai: 'Responsible Artificial Intelligence',
    guidance_ai: 'AI ke saath Guidance.\nTumhare saath Decisions.',
    disclaimer_sub: 'JanMitra AI kya karta hai, iski limits kahan hain, aur AI-powered welfare guidance use karne se pehle tumhari info kaise handle hoti hai — yeh samjho.',
    transparency_first: 'Transparency First',
    read_before_use: 'Use se pehle Padho',
    not_gov_service: 'JanMitra AI Government service nahi hai.',
    notice_001: 'Notice / 001',
    not_gov_desc: 'JanMitra AI sirf educational aur assistance purposes ke liye AI-generated guidance provide karta hai. Yeh official Government of India service nahi hai aur legal ya administrative approval nahi deta.',
    verify_info: 'Users ko action lene se pehle concerned government department se important information, eligibility conditions, documents, deadlines aur procedures independently verify karni chahiye.',
    operational_boundaries: 'Operational Boundaries',
    know_limits: 'Jaano ki AI kahan rukta hai.',
    assist_explain: 'Assist & Explain',
    janmitra_can: 'JANMITRA AI KAR SAKTA HAI',
    janmitra_cannot: 'JANMITRA AI NAHIN KAR SAKTA',
    can_1: 'Government scheme eligibility aur benefits explain kare.',
    can_2: 'Welfare services ke liye document requirements list kare.',
    can_3: 'Grievance guidance aur procedural steps provide kare.',
    can_4: 'Standardized complaint letter templates generate kare.',
    can_5: 'Major life events ke basis par relevant schemes identify kare.',
    cannot_1: 'Actual government applications process ya submit na kare.',
    cannot_2: 'Scheme eligibility, funding ya approval guarantee na kare.',
    cannot_3: 'Official government records access, modify ya verify na kare.',
    cannot_4: 'Legally binding advice ya representation na provide kare.',
    cannot_5: 'Tumhari taraf se administrative decisions na le.',
    data_protocol: 'Data Protocol',
    what_happens_data: 'Tumhare data ka kya hota hai?',
    data_desc: 'JanMitra AI ke through information kaise move karti hai — ek simple view.',
    you_interact: 'Tum interact karte ho',
    you_interact_desc: 'Jab tum iski features use karte ho toh chat questions ya documents system ko provide kiye jaate hain.',
    system_processes: 'System process karta hai',
    system_processes_desc: 'Information process hoti hai guidance, OCR results ya relevant responses generate karne ke liye.',
    sensitive_leave: 'Sensitive files chali jaati hain',
    sensitive_leave_desc: 'Upload kiye gaye documents process hote hain aur turant delete ho jaate hain. Chat conversations permanently store nahi hote.',
    no_identity_vault: 'No identity vault',
    no_identity_vault_desc: 'Koi Aadhaar, bank ya identity data store nahi hota.',
    anonymous_telemetry: 'Anonymous telemetry',
    anonymous_telemetry_desc: 'Sirf anonymised ratings aur comments retain kiye jaate hain.',
    local_knowledge: 'Local knowledge',
    local_knowledge_desc: 'Scheme aur FAQ information local data files use karti hain.',
    browser_preferences: 'Browser preferences',
    browser_preferences_desc: 'localStorage language aur theme preferences store karta hai.',
    external_processing: 'External processing:',
    external_processing_desc: 'JanMitra AI LLM inference ke liye Groq API use karta hai, jo Groq ki privacy policy ke subject hai.',
    behind_janmitra: 'JanMitra AI ke peeche kya hai?',
    system_desc: 'JanMitra AI HCLTech hackathon ke liye banaya gaya AI-powered welfare assistance tool hai.',
    verify_official: 'Official sources par continue karo.',
    verify_desc: 'Hamesha appropriate government portal ke saath directly important information verify karo.',
    responsible_ai_principle: 'JANMITRA AI RESPONSIBLE AI PRINCIPLE',
    principle_text: 'AI ko government information ko samajhne mein aasan banana chahiye — government hone ka dikhawa nahi karna chahiye.',

    // ===== ADMIN PAGE =====
    live_system: 'LIVE SYSTEM OVERVIEW',
    see_inside: 'Dekho kya ho raha hai\nJanMitra AI ke andar.',
    admin_desc: 'Real citizen interactions, AI usage aur feedback — directly current application logs se present kiye gaye.',
    latest_metrics: 'Latest metrics',
    refresh_dashboard: 'Refresh dashboard',
    ai_queries: 'AI Queries',
    total_conversations: 'Total conversations handled',
    positive: 'Positive',
    helpful_responses: 'Helpful responses reported',
    needs_work: 'Needs Work',
    negative_responses: 'Negative responses reported',
    satisfaction: 'Satisfaction',
    overall_feedback: 'Overall feedback performance',
    discovery: 'Discovery',
    what_ask_most: 'Citizens sab se zyada kya poochhte hain.',
    activity: 'Activity',
    feedback_feed: 'Citizen feedback feed.',
    no_query: 'Abhi tak koi query activity nahi.',
    no_feedback: 'Abhi tak koi feedback record nahi hua.',
    data_integrity: 'DATA INTEGRITY',
    data_integrity_desc: 'Yahan dikhi gayi har number actual JanMitra AI activity se aati hai. Koi demo statistics ya fabricated engagement numbers insert nahi kiye gaye.',
  },
  en: {
  // ===== NAVBAR =====
  search_placeholder: 'Search schemes, services or questions...',
  ask_ai: 'Ask AI',

  // ===== SIDEBAR =====
  explore: 'Explore JanMitra AI',
  what_help: 'What can we help you with today?',
  choose_service: 'Choose a service or ask the AI assistant directly.',
  start_here: 'Start here',
  home: 'Home',
  home_desc: 'Your JanMitra AI starting point',
  ask_janmitra: 'Ask JanMitra AI',
  ask_desc: 'Get instant welfare guidance',
  citizen_tools: 'Citizen tools',
  scheme_finder: 'Scheme Finder',
  scheme_desc: 'Discover benefits',
  checklist: 'Checklist',
  checklist_desc: 'Prepare documents',
  grievance: 'Grievance',
  grievance_desc: 'Resolve an issue',
  feedback: 'Feedback',
  responsible_ai: 'Responsible AI',
  admin: 'Admin',
  independent_tool: 'Independent assistance tool',
  not_official: 'Not an official Government service.',

  // ===== HOME PAGE =====
  hero_badge: 'AI-Powered · Uttar Pradesh',
  hero_title: 'Government schemes shouldn\'t feel complicated.',
  hero_sub: 'JanMitra AI helps citizens understand welfare schemes, documents, eligibility and government services without confusing paperwork.',
  start_here_btn: 'START HERE',
  ask_janmitra_btn: 'Ask JanMitra AI',
  discover_schemes: 'Discover my schemes',
  what_need: 'WHAT DO YOU NEED?',
  choose_task: 'Choose a task.\nWe\'ll guide you.',
  find_schemes: 'Find Schemes',
  find_schemes_desc: 'Discover government schemes based on your age, occupation and category.',
  documents: 'Documents',
  documents_desc: 'Know exactly what documents you need before visiting an office.',
  raise_grievance: 'Raise a Grievance',
  raise_grievance_desc: 'Understand complaint procedures and generate a formal grievance.',
  built_to: 'Built to make public services easier to understand.',
  built_desc: 'One simple interface for welfare information, document guidance and citizen assistance.',
  beneficiaries: 'Beneficiaries Covered',
  welfare_schemes: 'Welfare Schemes',
  ai_assistance: 'AI Assistance',
  uttar_pradesh: 'Uttar Pradesh Focus',
  need_human_help: 'NEED HUMAN HELP?',
  important_helplines: 'Important Helplines',

  // ===== CHAT PAGE =====
  online: 'JANMITRA AI IS ONLINE',
  ask: 'Ask.\nUnderstand.\nTake action.',
  chat_sub: 'Simple guidance for welfare schemes, ration cards, documents and government services in Uttar Pradesh.',
  current_session: 'Current Session',
  new_chat: 'New chat',
  your_questions: 'Your questions will appear here.',
  suggested_topics: 'Suggested Topics',
  chat_welcome: 'Hello! I\'m JanMitra AI, your welfare assistance guide for Uttar Pradesh. Tell me what you\'re trying to do and I\'ll help you understand the next steps.',
  ration_cards: 'Ration Cards',
  welfare_schemes_chat: 'Welfare Schemes',
  documents_chat: 'Documents',
  grievances_chat: 'Grievances',
  what_help_today: 'What can I help you with today?',
  ask_anything: 'Ask JanMitra AI anything...',
  ai_guidance: 'AI guidance only. Verify important information with official sources.',
  export: 'Export',
  clear: 'Clear',

  // ===== SCHEMES PAGE =====
  personalized_welfare: 'Personalized Welfare Discovery',
  schemes_title: 'Government schemes made for your profile.',
  schemes_sub: 'Tell us a few basic details and JanMitra AI will match your profile with relevant welfare schemes, benefits and required documents.',
  profile_details: 'Profile Details',
  tell_about_self: 'Tell us about yourself',
  your_age: 'Your Age',
  example_age: 'Example: 45',
  what_do: 'What do you do?',
  farmer: 'Farmer / Kisan',
  labour: 'Daily Wage Labour',
  student: 'Student',
  unemployed: 'Unemployed / Homemaker',
  other: 'Other / Salaried',
  social_category: 'Social Category',
  annual_income: 'Annual Family Income',
  optional: 'OPTIONAL',
  find_my_schemes: 'Find My Schemes',
  privacy_first: 'Privacy first',
  privacy_desc: 'Your profile is only used to calculate scheme matches.',
  your_results: 'Your Results',
  recommended_schemes: 'Recommended schemes',
  matching_complete: 'Matching Complete',
  schemes_found: 'schemes found for you',
  what_you_get: 'What You Get',
  documents_needed: 'Documents Needed',
  visit_official: 'Visit Official Portal',
  important: 'Important',
  scheme_disclaimer: 'JanMitra AI provides AI-generated guidance for educational purposes only. Verify important information with official sources.',
  your_matches: 'Your matches will appear here',
  complete_profile: 'Complete your profile and we\'ll search available welfare schemes for suitable matches.',
  eligibility: 'Eligibility',
  benefits: 'Benefits',

  // ===== CHECKLIST PAGE =====
  doc_prep_desk: 'DOCUMENT PREPARATION DESK',
  checklist_title: 'Get your documents ready before you go.',
  checklist_sub: 'Choose the government service you\'re applying for. JanMitra AI will prepare a clear document checklist for you.',
  gov_service: 'Government Service',
  choose_service: 'Choose your service',
  select_service: 'Select service',
  collect_docs: 'Collect documents',
  tick_ready: 'Tick each document when ready.',
  take_checklist: 'Take your checklist',
  print_save: 'Print it or save it as PDF.',
  quick_tip: 'Quick tip',
  tip_text: 'Keep originals and photocopies together before visiting the office.',
  waiting_service: 'WAITING FOR SERVICE',
  checklist_here: 'Your checklist will appear here.',
  select_left: 'Select a government service from the left panel to begin.',
  doc_requirement: 'DOCUMENT REQUIREMENT SHEET',
  processing: 'PROCESSING',
  application_fee: 'APPLICATION FEE',
  doc_readiness: 'Document readiness',
  collected: 'collected',
  required_docs: 'Required documents',
  required: 'Required',
  optional_badge: 'Optional',
  req_note: 'Requirements may vary depending on your case. Confirm important details with the respective department before submission.',

  // ===== GRIEVANCE PAGE =====
  citizen_resolution: 'Citizen Resolution Desk',
  grievance_title: 'Don\'t know where to raise your complaint?',
  grievance_sub: 'Choose your issue, follow the official escalation path, and prepare a formal complaint without getting lost in the process.',
  guided_process: 'Guided Process',
  three_stages: '3 Simple Stages',
  identify: 'Identify',
  resolve: 'Resolve',
  escalate: 'Escalate',
  start_here_grievance: 'Start here',
  what_went_wrong: 'What went wrong?',
  resolution_route: 'Resolution Route',
  follow_path: 'Follow your escalation path',
  escalation_tool: 'Escalation Tool',
  complaint_title: 'Turn your issue into a formal complaint.',
  complaint_sub: 'Provide the essential details and JanMitra AI will prepare a structured complaint draft for the concerned authority.',
  your_details: 'Your Details',
  name_location: 'Name and location information',
  describe_problem: 'Describe Problem',
  explain_happened: 'Explain exactly what happened',
  get_draft: 'Get Draft',
  ready_letter: 'Receive a ready complaint letter',
  complaint_builder: 'Complaint Builder',
  citizen_info: 'Citizen Information',
  form_data: 'Form Data',
  full_name: 'Full Name',
  district: 'District',
  block_tehsil: 'Block / Tehsil',
  village_ward: 'Village / Ward',
  issue_type: 'Issue Type',
  select_category: '— Select Official Issue Category —',
  issue_desc: 'Description of Issue',
  incident_date: 'Date of Incident',
  previous_complaint: 'Previous Complaint No.',
  generate_complaint: 'Generate Complaint Draft',
  document_ready: 'Document Ready',
  your_complaint: 'Your complaint draft',
  generated: 'Generated',
  formal_letter: 'Formal Letter',
  complaint_draft: 'Complaint Draft',
  what_now: 'What now?',
  submission_route: 'Submission Route',
  need_direct_help: 'Need direct help?',
  official_contacts: 'Official Contacts',
  current_case: 'Current Case',
  actions: 'Actions',
  action: 'Action',

  // ===== FEEDBACK PAGE =====
  citizen_voice: 'Citizen Voice',
  feedback_title: 'Tell us what actually worked.',
  feedback_sub: 'One rating can help make JanMitra AI clearer, faster and more useful for the next citizen.',
  your_experience: 'Your Experience',
  how_did_do: 'How did JanMitra AI do?',
  your_rating: 'Your Rating',
  select_rating: 'Select 1 — 5',
  what_reviewing: 'What are you reviewing?',
  choose_feature: 'Choose the part you used.',
  speak_freely: 'Speak Freely',
  what_change: 'What should we change?',
  feedback_placeholder: 'Write your experience here...',
  feedback_used: 'Feedback is used to improve JanMitra AI',
  send_feedback: 'Send Feedback',
  feedback_received: 'Feedback Received',
  thank_you: 'Thank you for helping us improve.',
  what_happens_next: 'What happens next',
  feedback_impact: 'Your feedback doesn\'t stop here.',
  improve_accuracy: 'Improve AI Accuracy',
  improve_accuracy_desc: 'Ratings help identify where AI answers can become clearer and more accurate.',
  serve_more: 'Serve More Citizens',
  serve_more_desc: 'Better experiences make welfare information easier to access across Uttar Pradesh.',
  build_trust: 'Build Responsible AI',
  build_trust_desc: 'Negative feedback helps surface potential issues that require attention.',
  accuracy: 'ACCURACY',
  access: 'ACCESS',
  trust: 'TRUST',
  feedback_disclaimer: 'JanMitra AI provides AI-generated guidance for educational purposes only. It is not an official Government of India service.',

  // ===== DISCLAIMER PAGE =====
  trust_charter: 'Trust Charter',
  responsible_ai: 'Responsible Artificial Intelligence',
  guidance_ai: 'Guidance with AI.\nDecisions with you.',
  disclaimer_sub: 'Understand what JanMitra AI does, where its limits are, and how your information is handled before using AI-powered welfare guidance.',
  transparency_first: 'TRANSPARENCY FIRST',
  read_before_use: 'READ BEFORE USE',
  not_gov_service: 'JanMitra AI is not a Government service.',
  notice_001: 'NOTICE / 001',
  not_gov_desc: 'JanMitra AI provides AI-generated guidance for educational and assistance purposes only. It is not an official Government of India service and does not provide legal or administrative approval.',
  verify_info: 'Users should independently verify important information, eligibility conditions, documents, deadlines and procedures with the respective government department before taking action.',
  operational_boundaries: 'Operational Boundaries',
  know_limits: 'Know where the AI stops.',
  assist_explain: 'Assist & Explain',
  janmitra_can: 'JANMITRA AI CAN',
  janmitra_cannot: 'JANMITRA AI CANNOT',
  can_1: 'Explain government scheme eligibility and benefits.',
  can_2: 'List document requirements for welfare services.',
  can_3: 'Provide grievance guidance and procedural steps.',
  can_4: 'Generate standardized complaint letter templates.',
  can_5: 'Identify relevant schemes based on major life events.',
  cannot_1: 'Process or submit actual government applications.',
  cannot_2: 'Guarantee scheme eligibility, funding or approval.',
  cannot_3: 'Access, modify or verify official government records.',
  cannot_4: 'Provide legally binding advice or representation.',
  cannot_5: 'Make administrative decisions on your behalf.',
  data_protocol: 'Data Protocol',
  what_happens_data: 'What happens to your data?',
  data_desc: 'A simple view of how information moves through JanMitra AI.',
  you_interact: 'You interact',
  you_interact_desc: 'Chat questions or documents are provided to the system when you use its features.',
  system_processes: 'System processes',
  system_processes_desc: 'Information is processed to generate guidance, OCR results or relevant responses.',
  sensitive_leave: 'Sensitive files leave',
  sensitive_leave_desc: 'Uploaded documents are processed and immediately deleted. Chat conversations are not permanently stored.',
  no_identity_vault: 'No identity vault',
  no_identity_vault_desc: 'No Aadhaar, bank or identity data is stored.',
  anonymous_telemetry: 'Anonymous telemetry',
  anonymous_telemetry_desc: 'Only anonymised ratings and comments are retained.',
  local_knowledge: 'Local knowledge',
  local_knowledge_desc: 'Scheme and FAQ information uses local data files.',
  browser_preferences: 'Browser preferences',
  browser_preferences_desc: 'localStorage stores language and theme preferences.',
  external_processing: 'External processing:',
  external_processing_desc: 'JanMitra AI uses Groq API for LLM inference, subject to Groq\'s privacy policy.',
  behind_janmitra: 'What\'s behind JanMitra AI?',
  system_desc: 'JanMitra AI is an AI-powered welfare assistance tool built for the HCLTech hackathon.',
  verify_official: 'Continue on official sources.',
  verify_desc: 'Always verify important information directly with the appropriate government portal.',
  responsible_ai_principle: 'JANMITRA AI RESPONSIBLE AI PRINCIPLE',
  principle_text: 'AI should make government information easier to understand — not pretend to be the government.',

  // ===== ADMIN PAGE =====
  live_system: 'LIVE SYSTEM OVERVIEW',
  see_inside: 'See what\'s happening inside JanMitra AI.',
  admin_desc: 'Real citizen interactions, AI usage and feedback — presented directly from the current application logs.',
  latest_metrics: 'Latest metrics',
  refresh_dashboard: 'Refresh dashboard',
  ai_queries: 'AI Queries',
  total_conversations: 'Total conversations handled',
  positive: 'Positive',
  helpful_responses: 'Helpful responses reported',
  needs_work: 'Needs Work',
  negative_responses: 'Negative responses reported',
  satisfaction: 'Satisfaction',
  overall_feedback: 'Overall feedback performance',
  discovery: 'Discovery',
  what_ask_most: 'What citizens ask the most.',
  activity: 'Activity',
  feedback_feed: 'Citizen feedback feed.',
  no_query: 'No query activity yet.',
  no_feedback: 'No feedback recorded yet.',
  data_integrity: 'DATA INTEGRITY',
  data_integrity_desc: 'Every number shown here comes from actual JanMitra AI activity. No demo statistics or fabricated engagement numbers are inserted.',
}
}
// ... (baaki sab same hai)
export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en')

  useEffect(() => {
    const saved = localStorage.getItem('janmitra_lang') || 'en'
    setLanguage(saved)
    applyTranslations(saved)  // ✅ Always apply, no if condition
  }, [])

  const applyTranslations = (lang) => {
    const translations = TRANSLATIONS[lang] || {}  // ✅ No if condition
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n')
      if (translations[key]) {
        el.textContent = translations[key]
      }
    })
  }

  const changeLanguage = (lang) => {
    setLanguage(lang)
    localStorage.setItem('janmitra_lang', lang)
    applyTranslations(lang)  // ✅ Always apply
    window.dispatchEvent(new Event('languageChange'))
  }

  const t = (key) => {
    const translations = TRANSLATIONS[language] || {}
    return translations[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}